SCRIPT TO TRAIN W2V/TFIDF ON TOKENIZED TEXT - code from aurelie

In [1]:
# import packages required

import pandas as pd
import os
import numpy as np
from gensim.models import Word2Vec, FastText
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim import corpora
from gensim.models import TfidfModel
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [ ]:
# spacy - skip - this outputs an error

if os.getcwd() == '/content': # on google drive
    import spacy
    nlp = spacy.load('en')
else: # on CRIS azure
    import scispacy
    import spacy
    nlp = spacy.load('en_core_sci_md')
    

In [5]:
!pip install scispacy

You should consider upgrading via the '/home/ubuntu/anaconda3/bin/python -m pip install --upgrade pip' command.


In [8]:
! pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_md-0.4.0.tar.gz

     |████████████████████████████████| 125.2 MB 108 kB/s eta 0:00:01    |███████▌                        | 29.3 MB 211 kB/s eta 0:07:34     |███████▌                        | 29.5 MB 230 kB/s eta 0:06:56     |████████████▍                   | 48.5 MB 284 kB/s eta 0:04:31     |█████████████▋                  | 53.2 MB 172 kB/s eta 0:06:57��██              | 70.7 MB 709 kB/s eta 0:01:17
  Created wheel for en-core-sci-md: filename=en_core_sci_md-0.4.0-py3-none-any.whl size=125733930 sha256=19855a88206d123b61748d5162a699ed089e3b6260b409fa8e9520a7c2a819e6
  Stored in directory: /home/ubuntu/.cache/pip/wheels/55/c0/ee/f9f0abbcbe0bd9da49c05b04aba66f0d259dd6af60b207c9d3
Successfully built en-core-sci-md
  Attempting uninstall: en-core-sci-md
    Found existing installation: en-core-sci-md 0.3.0
    Uninstalling en-core-sci-md-0.3.0:
      Successfully uninstalled en-core-sci-md-0.3.0
You should consider upgrading via the '/home/ubuntu/anaconda3/bin/python -m pip install --upgrade pip' comman

In [9]:
# spacy
import scispacy
import spacy
#nlp = spacy.load('en')
nlp = spacy.load('en_core_sci_md')

In [10]:
from spacy.lang.en.examples import sentences

## PREPARE TEXT FILE

In [18]:
def tokenize_spacy(df, text_col=None, tokenization_type='clean', outfile=None):
    tok_snts = []
    if outfile is not None: f = open(outfile, 'w', encoding='utf8')
    data = df if text_col is None else df[text_col]
    for snt in data:
        tkns = nlp.tokenizer(snt)
        if ('low' in tokenization_type) and ('wos' in tokenization_type):
            _tkns = [str(x.text).lower() for x in tkns if not x.is_space]
        elif 'wos' in tokenization_type:
            _tkns = [str(x.text) for x in tkns if not x.is_space]
        elif 'lem' in tokenization_type:
            _tkns = [str(x.lemma_).lower() for x in tkns if not x.is_space and not x.is_punct]
        elif 'stem' in tokenization_type:
            _tkns = [stemmer.stem(str(x.text).lower()) for x in tkns if not x.is_space and not x.is_punct]
        else: # clean by default
            _tkns = [str(x.text).lower() for x in tkns if not x.is_space and not x.is_punct]
        
        if outfile is not None: # flush to file if option selected
            f.write("{}\n".format("\t".join(_tkns)))
        else: # otherwise save in variable
            tok_snts.append(_tkns)

    return tok_snts if outfile is None else None


In [19]:
# PREPARE THE TXT FILE
#raw_file = '/home/ubuntu/data/mimic/tokenized_scispacy/noteevents_tkns.csv
raw_file = './NOTEEVENTS_all_text.csv'

In [20]:
df = pd.read_csv(raw_file)

In [21]:
df.head()

text
0  Coronary artery bypass graft (CABG)\n   Assess...
1  Subdural hemorrhage (SDH)\n   Assessment:\n   ...
2  Coronary artery bypass graft (CABG)\n   Assess...
3  Coronary artery bypass graft (CABG)\n   Assess...
4  Demographics\n   Day of intubation:\n   Day of...

In [25]:
# this step runs but the outfile seems to be empty? is it because text_col should be 'text'? this seems to have worked


#sentences = tokenize_spacy(df, text_col=None, tokenization_type='clean', outfile=raw_file,replace('.csv','_clean.txt'))
sentences = tokenize_spacy(df, text_col='text', tokenization_type='clean', outfile='./notes_clean.txt')

In [32]:
#numpy_array = df.to_numpy()

In [ ]:
#np.savetxt("noteevents_v2.txt", numpy_array, fmt='%s')

## INPUT DATA

In [37]:
# INPUT PARAMETERS

# tokenized text
#filename = '/home/ubuntu/data/mimic/tokenized_scispacy/noteevents_tkns_stem.txt' # with stemming
filename = './notes_clean.txt'

# w2v/fasttext params
size=300
window=10
min_count=5
workers=16

# sklearn - tfidf params
min_df=0.2
max_df=0.9
ngram_range=(1, 5)
max_features=1000

# gensim - tfidf params

In [38]:
class SentenceIterator: 
    def __init__(self, filepath): 
        self.filepath = filepath 

    def __iter__(self): 
        for line in open(self.filepath): 
            yield line.split("\t") 

In [39]:
sentences = SentenceIterator(filename) 

## TRAIN GLOVE

In [ ]:
!pip install glove # this is not working.. have to figure out how to make glove work here - or ask tao

In [31]:
# TRAIN AND SAVE GLOVE
import glove
from glove import Corpus, Glove


corpus = Corpus() #Creating a corpus object
corpus.fit(sentences, window=window) #Training the corpus to generate the co occurence matrix which is used in GloVe

glove = Glove(no_components=5, learning_rate=0.05) 
glove.fit(corpus.matrix, epochs=30, no_threads=4, verbose=True)
glove.add_dictionary(corpus.dictionary)
glove.save(filename.replace('.txt','_glove.model').replace('_tkns',''))

ModuleNotFoundError: No module named 'glove'

## TRAIN FASTEXT

In [40]:
# TRAIN AND SAVE FASTTEXT
ft_model = FastText(size=size, window=window, min_count=min_count)  # instantiate
ft_model.build_vocab(sentences=sentences)
ft_model.train(sentences=sentences, total_examples=sum(1 for _ in sentences), epochs=2)
#ft_model.save(filename.replace('.txt','_fasttext_win10_min5.dat').replace('_tkns',''))
ft_model.save(filename.replace('.txt','_fasttext_win10_min5_v2.dat'))

2021-02-23 17:03:53,717 : INFO : resetting layer weights
2021-02-23 17:04:09,017 : INFO : collecting all words and their counts
2021-02-23 17:04:09,019 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2021-02-23 17:04:10,177 : INFO : PROGRESS: at sentence #10000, processed 4750988 words, keeping 47253 word types
2021-02-23 17:04:11,350 : INFO : PROGRESS: at sentence #20000, processed 9517988 words, keeping 70404 word types
2021-02-23 17:04:12,516 : INFO : PROGRESS: at sentence #30000, processed 14217892 words, keeping 89904 word types
2021-02-23 17:04:13,270 : INFO : PROGRESS: at sentence #40000, processed 17342834 words, keeping 108098 word types
2021-02-23 17:04:13,746 : INFO : PROGRESS: at sentence #50000, processed 19317065 words, keeping 123739 word types
2021-02-23 17:04:14,224 : INFO : PROGRESS: at sentence #60000, processed 21292462 words, keeping 137319 word types
2021-02-23 17:04:14,719 : INFO : PROGRESS: at sentence #70000, processed 23293819 words,

2021-02-23 17:04:42,091 : INFO : PROGRESS: at sentence #700000, processed 128065898 words, keeping 685141 word types
2021-02-23 17:04:42,467 : INFO : PROGRESS: at sentence #710000, processed 129482719 words, keeping 690729 word types
2021-02-23 17:04:42,959 : INFO : PROGRESS: at sentence #720000, processed 131326251 words, keeping 698923 word types
2021-02-23 17:04:43,539 : INFO : PROGRESS: at sentence #730000, processed 133405061 words, keeping 707962 word types
2021-02-23 17:04:46,813 : INFO : PROGRESS: at sentence #740000, processed 146962855 words, keeping 765561 word types
2021-02-23 17:04:50,586 : INFO : PROGRESS: at sentence #750000, processed 162247244 words, keeping 810963 word types
2021-02-23 17:04:54,484 : INFO : PROGRESS: at sentence #760000, processed 178597370 words, keeping 851152 word types
2021-02-23 17:04:55,299 : INFO : PROGRESS: at sentence #770000, processed 181862498 words, keeping 853644 word types
2021-02-23 17:04:56,114 : INFO : PROGRESS: at sentence #780000, 

2021-02-23 17:05:37,158 : INFO : PROGRESS: at sentence #1400000, processed 341505124 words, keeping 1173366 word types
2021-02-23 17:05:39,789 : INFO : PROGRESS: at sentence #1410000, processed 352027794 words, keeping 1196703 word types
2021-02-23 17:05:43,500 : INFO : PROGRESS: at sentence #1420000, processed 365689697 words, keeping 1223064 word types
2021-02-23 17:05:44,306 : INFO : PROGRESS: at sentence #1430000, processed 368701155 words, keeping 1223883 word types
2021-02-23 17:05:44,485 : INFO : PROGRESS: at sentence #1440000, processed 369401663 words, keeping 1224097 word types
2021-02-23 17:05:44,564 : INFO : PROGRESS: at sentence #1450000, processed 369708850 words, keeping 1224238 word types
2021-02-23 17:05:44,642 : INFO : PROGRESS: at sentence #1460000, processed 370007394 words, keeping 1224371 word types
2021-02-23 17:05:44,722 : INFO : PROGRESS: at sentence #1470000, processed 370318348 words, keeping 1224472 word types
2021-02-23 17:05:44,817 : INFO : PROGRESS: at se

2021-02-23 17:06:28,169 : INFO : collected 1492743 word types from a corpus of 534796798 raw words and 2083180 sentences
2021-02-23 17:06:28,169 : INFO : Loading a fresh vocabulary
2021-02-23 17:06:29,998 : INFO : effective_min_count=5 retains 416342 unique words (27% of original 1492743, drops 1076401)
2021-02-23 17:06:29,999 : INFO : effective_min_count=5 leaves 533154263 word corpus (99% of original 534796798, drops 1642535)
2021-02-23 17:06:31,229 : INFO : deleting the raw counts dictionary of 1492743 items
2021-02-23 17:06:31,273 : INFO : sample=0.001 downsamples 35 most-common words
2021-02-23 17:06:31,274 : INFO : downsampling leaves estimated 476070309 word corpus (89.3% of prior 533154263)
2021-02-23 17:06:36,963 : INFO : estimated required memory for 416342 words, 1062221 buckets and 300 dimensions: 2583428840 bytes
2021-02-23 17:06:37,023 : INFO : resetting layer weights
2021-02-23 17:08:50,243 : INFO : training model with 3 workers on 416342 vocabulary and 300 features, usi

2021-02-23 17:10:02,447 : INFO : EPOCH 1 - PROGRESS: at 0.75% examples, 94766 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:03,548 : INFO : EPOCH 1 - PROGRESS: at 0.76% examples, 94774 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:04,626 : INFO : EPOCH 1 - PROGRESS: at 0.78% examples, 94805 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:05,684 : INFO : EPOCH 1 - PROGRESS: at 0.79% examples, 94862 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:06,772 : INFO : EPOCH 1 - PROGRESS: at 0.80% examples, 94892 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:07,858 : INFO : EPOCH 1 - PROGRESS: at 0.81% examples, 94935 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:08,931 : INFO : EPOCH 1 - PROGRESS: at 0.82% examples, 94985 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:10,031 : INFO : EPOCH 1 - PROGRESS: at 0.84% examples, 94963 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:10:11,134 : INFO : EPOCH 1 - PROGRESS: at 0.85% examples, 94961 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:11:22,579 : INFO : EPOCH 1 - PROGRESS: at 1.61% examples, 95405 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:23,629 : INFO : EPOCH 1 - PROGRESS: at 1.63% examples, 95369 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:24,672 : INFO : EPOCH 1 - PROGRESS: at 1.65% examples, 95272 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:25,705 : INFO : EPOCH 1 - PROGRESS: at 1.67% examples, 95249 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:26,759 : INFO : EPOCH 1 - PROGRESS: at 1.69% examples, 95219 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:27,805 : INFO : EPOCH 1 - PROGRESS: at 1.71% examples, 95132 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:28,890 : INFO : EPOCH 1 - PROGRESS: at 1.73% examples, 95072 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:29,937 : INFO : EPOCH 1 - PROGRESS: at 1.75% examples, 94979 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:11:31,025 : INFO : EPOCH 1 - PROGRESS: at 1.78% examples, 94914 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:12:42,702 : INFO : EPOCH 1 - PROGRESS: at 3.44% examples, 91005 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:43,892 : INFO : EPOCH 1 - PROGRESS: at 3.47% examples, 90942 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:44,905 : INFO : EPOCH 1 - PROGRESS: at 3.49% examples, 90914 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:46,088 : INFO : EPOCH 1 - PROGRESS: at 3.51% examples, 90853 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:47,130 : INFO : EPOCH 1 - PROGRESS: at 3.54% examples, 90848 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:48,270 : INFO : EPOCH 1 - PROGRESS: at 3.56% examples, 90768 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:49,313 : INFO : EPOCH 1 - PROGRESS: at 3.59% examples, 90762 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:50,424 : INFO : EPOCH 1 - PROGRESS: at 3.61% examples, 90697 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:12:51,425 : INFO : EPOCH 1 - PROGRESS: at 3.64% examples, 90670 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:14:06,215 : INFO : EPOCH 1 - PROGRESS: at 5.26% examples, 88369 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:07,499 : INFO : EPOCH 1 - PROGRESS: at 5.29% examples, 88335 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:08,744 : INFO : EPOCH 1 - PROGRESS: at 5.32% examples, 88308 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:09,995 : INFO : EPOCH 1 - PROGRESS: at 5.35% examples, 88281 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:11,003 : INFO : EPOCH 1 - PROGRESS: at 5.37% examples, 88296 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:12,200 : INFO : EPOCH 1 - PROGRESS: at 5.39% examples, 88230 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:13,456 : INFO : EPOCH 1 - PROGRESS: at 5.42% examples, 88205 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:14,697 : INFO : EPOCH 1 - PROGRESS: at 5.45% examples, 88180 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:14:15,698 : INFO : EPOCH 1 - PROGRESS: at 5.48% examples, 88197 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:15:29,246 : INFO : EPOCH 1 - PROGRESS: at 7.05% examples, 86855 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:30,352 : INFO : EPOCH 1 - PROGRESS: at 7.08% examples, 86851 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:31,493 : INFO : EPOCH 1 - PROGRESS: at 7.10% examples, 86817 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:32,594 : INFO : EPOCH 1 - PROGRESS: at 7.13% examples, 86811 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:33,683 : INFO : EPOCH 1 - PROGRESS: at 7.15% examples, 86789 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:34,712 : INFO : EPOCH 1 - PROGRESS: at 7.17% examples, 86780 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:35,770 : INFO : EPOCH 1 - PROGRESS: at 7.20% examples, 86763 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:36,841 : INFO : EPOCH 1 - PROGRESS: at 7.22% examples, 86744 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:15:37,929 : INFO : EPOCH 1 - PROGRESS: at 7.24% examples, 86720 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:16:50,666 : INFO : EPOCH 1 - PROGRESS: at 8.80% examples, 85694 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:51,696 : INFO : EPOCH 1 - PROGRESS: at 8.82% examples, 85688 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:52,874 : INFO : EPOCH 1 - PROGRESS: at 8.84% examples, 85656 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:53,888 : INFO : EPOCH 1 - PROGRESS: at 8.87% examples, 85653 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:55,137 : INFO : EPOCH 1 - PROGRESS: at 8.89% examples, 85627 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:56,145 : INFO : EPOCH 1 - PROGRESS: at 8.92% examples, 85644 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:57,386 : INFO : EPOCH 1 - PROGRESS: at 8.94% examples, 85603 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:58,388 : INFO : EPOCH 1 - PROGRESS: at 8.97% examples, 85604 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:16:59,596 : INFO : EPOCH 1 - PROGRESS: at 8.99% examples, 85585 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 17:18:12,150 : INFO : EPOCH 1 - PROGRESS: at 10.55% examples, 84929 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:13,224 : INFO : EPOCH 1 - PROGRESS: at 10.57% examples, 84918 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:14,273 : INFO : EPOCH 1 - PROGRESS: at 10.59% examples, 84912 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:15,296 : INFO : EPOCH 1 - PROGRESS: at 10.61% examples, 84911 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:16,388 : INFO : EPOCH 1 - PROGRESS: at 10.63% examples, 84899 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:17,487 : INFO : EPOCH 1 - PROGRESS: at 10.66% examples, 84884 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:18,611 : INFO : EPOCH 1 - PROGRESS: at 10.68% examples, 84881 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:19,702 : INFO : EPOCH 1 - PROGRESS: at 10.70% examples, 84865 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:18:20,856 : INFO : EPOCH 1 - PROGRESS: at 10.72% examples, 84859 words/s, in_qsize 5, out_

2021-02-23 17:19:34,852 : INFO : EPOCH 1 - PROGRESS: at 12.17% examples, 84350 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:35,870 : INFO : EPOCH 1 - PROGRESS: at 12.19% examples, 84347 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:37,049 : INFO : EPOCH 1 - PROGRESS: at 12.22% examples, 84337 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:38,088 : INFO : EPOCH 1 - PROGRESS: at 12.24% examples, 84333 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:39,223 : INFO : EPOCH 1 - PROGRESS: at 12.26% examples, 84330 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:40,344 : INFO : EPOCH 1 - PROGRESS: at 12.28% examples, 84315 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:41,448 : INFO : EPOCH 1 - PROGRESS: at 12.30% examples, 84317 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:19:42,615 : INFO : EPOCH 1 - PROGRESS: at 12.32% examples, 84296 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:19:43,664 : INFO : EPOCH 1 - PROGRESS: at 12.35% examples, 84305 words/s, in_qsize 5, out_

2021-02-23 17:20:58,872 : INFO : EPOCH 1 - PROGRESS: at 13.78% examples, 83840 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:20:59,922 : INFO : EPOCH 1 - PROGRESS: at 13.80% examples, 83835 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:01,006 : INFO : EPOCH 1 - PROGRESS: at 13.82% examples, 83825 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:02,142 : INFO : EPOCH 1 - PROGRESS: at 13.84% examples, 83823 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:03,186 : INFO : EPOCH 1 - PROGRESS: at 13.86% examples, 83818 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:04,199 : INFO : EPOCH 1 - PROGRESS: at 13.88% examples, 83819 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:05,312 : INFO : EPOCH 1 - PROGRESS: at 13.90% examples, 83808 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:06,315 : INFO : EPOCH 1 - PROGRESS: at 13.92% examples, 83810 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:21:07,391 : INFO : EPOCH 1 - PROGRESS: at 13.94% examples, 83803 words/s, in_qsize 5, out_

2021-02-23 17:22:17,713 : INFO : EPOCH 1 - PROGRESS: at 16.00% examples, 84836 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:18,717 : INFO : EPOCH 1 - PROGRESS: at 16.03% examples, 84860 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:19,727 : INFO : EPOCH 1 - PROGRESS: at 16.07% examples, 84883 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:20,728 : INFO : EPOCH 1 - PROGRESS: at 16.10% examples, 84907 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:21,755 : INFO : EPOCH 1 - PROGRESS: at 16.14% examples, 84939 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:22,785 : INFO : EPOCH 1 - PROGRESS: at 16.18% examples, 84970 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:23,981 : INFO : EPOCH 1 - PROGRESS: at 16.22% examples, 84984 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:22:24,983 : INFO : EPOCH 1 - PROGRESS: at 16.27% examples, 85030 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:22:25,985 : INFO : EPOCH 1 - PROGRESS: at 16.30% examples, 85053 words/s, in_qsize 5, out_

2021-02-23 17:23:34,268 : INFO : EPOCH 1 - PROGRESS: at 18.71% examples, 86543 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:35,292 : INFO : EPOCH 1 - PROGRESS: at 18.74% examples, 86561 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:36,311 : INFO : EPOCH 1 - PROGRESS: at 18.78% examples, 86579 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:37,327 : INFO : EPOCH 1 - PROGRESS: at 18.82% examples, 86597 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:38,358 : INFO : EPOCH 1 - PROGRESS: at 18.85% examples, 86614 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:23:39,361 : INFO : EPOCH 1 - PROGRESS: at 18.89% examples, 86643 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:40,364 : INFO : EPOCH 1 - PROGRESS: at 18.92% examples, 86663 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:41,380 : INFO : EPOCH 1 - PROGRESS: at 18.96% examples, 86681 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:23:42,384 : INFO : EPOCH 1 - PROGRESS: at 18.99% examples, 86700 words/s, in_qsize 5, out_

2021-02-23 17:24:50,406 : INFO : EPOCH 1 - PROGRESS: at 21.37% examples, 87902 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:51,477 : INFO : EPOCH 1 - PROGRESS: at 21.41% examples, 87921 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:52,478 : INFO : EPOCH 1 - PROGRESS: at 21.44% examples, 87938 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:53,502 : INFO : EPOCH 1 - PROGRESS: at 21.48% examples, 87962 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:54,704 : INFO : EPOCH 1 - PROGRESS: at 21.52% examples, 87969 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:55,720 : INFO : EPOCH 1 - PROGRESS: at 21.56% examples, 87993 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:56,738 : INFO : EPOCH 1 - PROGRESS: at 21.60% examples, 88019 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:57,744 : INFO : EPOCH 1 - PROGRESS: at 21.64% examples, 88035 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:24:58,754 : INFO : EPOCH 1 - PROGRESS: at 21.68% examples, 88052 words/s, in_qsize 5, out_

2021-02-23 17:26:06,347 : INFO : EPOCH 1 - PROGRESS: at 24.01% examples, 89030 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:07,385 : INFO : EPOCH 1 - PROGRESS: at 24.05% examples, 89041 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:08,428 : INFO : EPOCH 1 - PROGRESS: at 24.08% examples, 89052 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:26:09,461 : INFO : EPOCH 1 - PROGRESS: at 24.12% examples, 89064 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:10,464 : INFO : EPOCH 1 - PROGRESS: at 24.15% examples, 89079 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:11,516 : INFO : EPOCH 1 - PROGRESS: at 24.20% examples, 89099 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:12,541 : INFO : EPOCH 1 - PROGRESS: at 24.26% examples, 89121 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:13,550 : INFO : EPOCH 1 - PROGRESS: at 24.31% examples, 89136 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:26:14,629 : INFO : EPOCH 1 - PROGRESS: at 24.37% examples, 89153 words/s, in_qsize 5, out_

2021-02-23 17:27:25,288 : INFO : EPOCH 1 - PROGRESS: at 27.88% examples, 90289 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:26,372 : INFO : EPOCH 1 - PROGRESS: at 27.94% examples, 90304 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:27,479 : INFO : EPOCH 1 - PROGRESS: at 27.99% examples, 90317 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:28,579 : INFO : EPOCH 1 - PROGRESS: at 28.06% examples, 90339 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:29,688 : INFO : EPOCH 1 - PROGRESS: at 28.11% examples, 90351 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:27:30,799 : INFO : EPOCH 1 - PROGRESS: at 28.17% examples, 90372 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:31,873 : INFO : EPOCH 1 - PROGRESS: at 28.22% examples, 90386 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:32,879 : INFO : EPOCH 1 - PROGRESS: at 28.27% examples, 90407 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:27:33,880 : INFO : EPOCH 1 - PROGRESS: at 28.32% examples, 90420 words/s, in_qsize 5, out_

2021-02-23 17:28:46,729 : INFO : EPOCH 1 - PROGRESS: at 32.08% examples, 91455 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:47,732 : INFO : EPOCH 1 - PROGRESS: at 32.13% examples, 91467 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:48,761 : INFO : EPOCH 1 - PROGRESS: at 32.18% examples, 91490 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:49,949 : INFO : EPOCH 1 - PROGRESS: at 32.24% examples, 91495 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:50,954 : INFO : EPOCH 1 - PROGRESS: at 32.30% examples, 91514 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:52,003 : INFO : EPOCH 1 - PROGRESS: at 32.35% examples, 91529 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:53,113 : INFO : EPOCH 1 - PROGRESS: at 32.41% examples, 91540 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:54,211 : INFO : EPOCH 1 - PROGRESS: at 32.47% examples, 91558 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:28:55,227 : INFO : EPOCH 1 - PROGRESS: at 32.52% examples, 91569 words/s, in_qsize 5, out_

2021-02-23 17:30:04,952 : INFO : EPOCH 1 - PROGRESS: at 35.09% examples, 92288 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:05,973 : INFO : EPOCH 1 - PROGRESS: at 35.09% examples, 92280 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:07,021 : INFO : EPOCH 1 - PROGRESS: at 35.10% examples, 92278 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:08,034 : INFO : EPOCH 1 - PROGRESS: at 35.10% examples, 92275 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:09,073 : INFO : EPOCH 1 - PROGRESS: at 35.10% examples, 92274 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:10,187 : INFO : EPOCH 1 - PROGRESS: at 35.10% examples, 92269 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:11,277 : INFO : EPOCH 1 - PROGRESS: at 35.11% examples, 92266 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:30:12,328 : INFO : EPOCH 1 - PROGRESS: at 35.11% examples, 92261 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:30:13,444 : INFO : EPOCH 1 - PROGRESS: at 35.11% examples, 92256 words/s, in_qsize 5, out_

2021-02-23 17:31:23,545 : INFO : EPOCH 1 - PROGRESS: at 35.33% examples, 92051 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:24,627 : INFO : EPOCH 1 - PROGRESS: at 35.33% examples, 92048 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:25,719 : INFO : EPOCH 1 - PROGRESS: at 35.33% examples, 92047 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:26,748 : INFO : EPOCH 1 - PROGRESS: at 35.34% examples, 92046 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:27,787 : INFO : EPOCH 1 - PROGRESS: at 35.34% examples, 92040 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:28,886 : INFO : EPOCH 1 - PROGRESS: at 35.34% examples, 92039 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:29,891 : INFO : EPOCH 1 - PROGRESS: at 35.35% examples, 92038 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:30,912 : INFO : EPOCH 1 - PROGRESS: at 35.35% examples, 92034 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:31:32,014 : INFO : EPOCH 1 - PROGRESS: at 35.35% examples, 92030 words/s, in_qsize 5, out_

2021-02-23 17:32:42,581 : INFO : EPOCH 1 - PROGRESS: at 35.61% examples, 91799 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:43,643 : INFO : EPOCH 1 - PROGRESS: at 35.62% examples, 91793 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:44,710 : INFO : EPOCH 1 - PROGRESS: at 35.62% examples, 91790 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:45,781 : INFO : EPOCH 1 - PROGRESS: at 35.62% examples, 91786 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:46,830 : INFO : EPOCH 1 - PROGRESS: at 35.63% examples, 91786 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:47,897 : INFO : EPOCH 1 - PROGRESS: at 35.63% examples, 91783 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:49,037 : INFO : EPOCH 1 - PROGRESS: at 35.63% examples, 91778 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:50,172 : INFO : EPOCH 1 - PROGRESS: at 35.64% examples, 91773 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:32:51,288 : INFO : EPOCH 1 - PROGRESS: at 35.64% examples, 91771 words/s, in_qsize 5, out_

2021-02-23 17:34:02,352 : INFO : EPOCH 1 - PROGRESS: at 35.86% examples, 91586 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:03,417 : INFO : EPOCH 1 - PROGRESS: at 35.86% examples, 91584 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:04,446 : INFO : EPOCH 1 - PROGRESS: at 35.87% examples, 91581 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:05,499 : INFO : EPOCH 1 - PROGRESS: at 35.87% examples, 91579 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:06,605 : INFO : EPOCH 1 - PROGRESS: at 35.87% examples, 91578 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:07,661 : INFO : EPOCH 1 - PROGRESS: at 35.88% examples, 91577 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:08,789 : INFO : EPOCH 1 - PROGRESS: at 35.88% examples, 91574 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:09,802 : INFO : EPOCH 1 - PROGRESS: at 35.88% examples, 91575 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:34:10,857 : INFO : EPOCH 1 - PROGRESS: at 35.89% examples, 91573 words/s, in_qsize 5, out_

2021-02-23 17:35:21,875 : INFO : EPOCH 1 - PROGRESS: at 36.09% examples, 91444 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:23,001 : INFO : EPOCH 1 - PROGRESS: at 36.09% examples, 91441 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:24,084 : INFO : EPOCH 1 - PROGRESS: at 36.09% examples, 91440 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:25,095 : INFO : EPOCH 1 - PROGRESS: at 36.10% examples, 91441 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:26,177 : INFO : EPOCH 1 - PROGRESS: at 36.10% examples, 91434 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:27,223 : INFO : EPOCH 1 - PROGRESS: at 36.10% examples, 91429 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:35:28,267 : INFO : EPOCH 1 - PROGRESS: at 36.11% examples, 91429 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:29,377 : INFO : EPOCH 1 - PROGRESS: at 36.11% examples, 91427 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:35:30,466 : INFO : EPOCH 1 - PROGRESS: at 36.11% examples, 91426 words/s, in_qsize 5, out_

2021-02-23 17:36:40,505 : INFO : EPOCH 1 - PROGRESS: at 36.30% examples, 91294 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:41,576 : INFO : EPOCH 1 - PROGRESS: at 36.30% examples, 91295 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:42,617 : INFO : EPOCH 1 - PROGRESS: at 36.31% examples, 91294 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:43,676 : INFO : EPOCH 1 - PROGRESS: at 36.31% examples, 91291 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:44,687 : INFO : EPOCH 1 - PROGRESS: at 36.31% examples, 91288 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:45,788 : INFO : EPOCH 1 - PROGRESS: at 36.31% examples, 91283 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:46,953 : INFO : EPOCH 1 - PROGRESS: at 36.32% examples, 91282 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:48,046 : INFO : EPOCH 1 - PROGRESS: at 36.32% examples, 91280 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:36:49,189 : INFO : EPOCH 1 - PROGRESS: at 36.32% examples, 91276 words/s, in_qsize 5, out_

2021-02-23 17:37:59,345 : INFO : EPOCH 1 - PROGRESS: at 36.81% examples, 91013 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:00,422 : INFO : EPOCH 1 - PROGRESS: at 36.82% examples, 91002 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:01,484 : INFO : EPOCH 1 - PROGRESS: at 36.84% examples, 90991 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:02,487 : INFO : EPOCH 1 - PROGRESS: at 36.85% examples, 90984 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:03,514 : INFO : EPOCH 1 - PROGRESS: at 36.86% examples, 90975 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:04,559 : INFO : EPOCH 1 - PROGRESS: at 36.88% examples, 90965 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:05,606 : INFO : EPOCH 1 - PROGRESS: at 36.89% examples, 90955 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:38:06,622 : INFO : EPOCH 1 - PROGRESS: at 36.90% examples, 90942 words/s, in_qsize 6, out_qsize 0
2021-02-23 17:38:07,680 : INFO : EPOCH 1 - PROGRESS: at 36.92% examples, 90931 words/s, in_qsize 5, out_

2021-02-23 17:39:16,714 : INFO : EPOCH 1 - PROGRESS: at 38.97% examples, 90435 words/s, in_qsize 6, out_qsize 0
2021-02-23 17:39:17,873 : INFO : EPOCH 1 - PROGRESS: at 39.13% examples, 90427 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:18,958 : INFO : EPOCH 1 - PROGRESS: at 39.29% examples, 90422 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:19,991 : INFO : EPOCH 1 - PROGRESS: at 39.44% examples, 90419 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:21,131 : INFO : EPOCH 1 - PROGRESS: at 39.61% examples, 90412 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:22,201 : INFO : EPOCH 1 - PROGRESS: at 39.77% examples, 90407 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:23,313 : INFO : EPOCH 1 - PROGRESS: at 39.92% examples, 90401 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:24,420 : INFO : EPOCH 1 - PROGRESS: at 40.08% examples, 90395 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:39:25,433 : INFO : EPOCH 1 - PROGRESS: at 40.24% examples, 90393 words/s, in_qsize 5, out_

2021-02-23 17:40:37,323 : INFO : EPOCH 1 - PROGRESS: at 43.31% examples, 90485 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:38,368 : INFO : EPOCH 1 - PROGRESS: at 43.32% examples, 90490 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:39,422 : INFO : EPOCH 1 - PROGRESS: at 43.33% examples, 90495 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:40,474 : INFO : EPOCH 1 - PROGRESS: at 43.34% examples, 90496 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:41,554 : INFO : EPOCH 1 - PROGRESS: at 43.35% examples, 90500 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:42,623 : INFO : EPOCH 1 - PROGRESS: at 43.37% examples, 90505 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:43,640 : INFO : EPOCH 1 - PROGRESS: at 43.38% examples, 90508 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:44,760 : INFO : EPOCH 1 - PROGRESS: at 43.39% examples, 90509 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:40:45,797 : INFO : EPOCH 1 - PROGRESS: at 43.40% examples, 90515 words/s, in_qsize 5, out_

2021-02-23 17:41:57,319 : INFO : EPOCH 1 - PROGRESS: at 44.15% examples, 90703 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:41:58,380 : INFO : EPOCH 1 - PROGRESS: at 44.16% examples, 90708 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:41:59,475 : INFO : EPOCH 1 - PROGRESS: at 44.18% examples, 90712 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:42:00,496 : INFO : EPOCH 1 - PROGRESS: at 44.19% examples, 90714 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:42:01,506 : INFO : EPOCH 1 - PROGRESS: at 44.20% examples, 90716 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:42:02,599 : INFO : EPOCH 1 - PROGRESS: at 44.21% examples, 90718 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:42:03,637 : INFO : EPOCH 1 - PROGRESS: at 44.22% examples, 90719 words/s, in_qsize 6, out_qsize 0
2021-02-23 17:42:04,710 : INFO : EPOCH 1 - PROGRESS: at 44.23% examples, 90719 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:42:05,828 : INFO : EPOCH 1 - PROGRESS: at 44.24% examples, 90721 words/s, in_qsize 5, out_

2021-02-23 17:43:16,614 : INFO : EPOCH 1 - PROGRESS: at 44.95% examples, 90889 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:43:17,696 : INFO : EPOCH 1 - PROGRESS: at 44.96% examples, 90892 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:18,794 : INFO : EPOCH 1 - PROGRESS: at 44.97% examples, 90895 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:19,920 : INFO : EPOCH 1 - PROGRESS: at 44.99% examples, 90896 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:21,010 : INFO : EPOCH 1 - PROGRESS: at 45.00% examples, 90899 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:22,065 : INFO : EPOCH 1 - PROGRESS: at 45.01% examples, 90903 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:23,095 : INFO : EPOCH 1 - PROGRESS: at 45.02% examples, 90908 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:24,113 : INFO : EPOCH 1 - PROGRESS: at 45.03% examples, 90910 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:43:25,266 : INFO : EPOCH 1 - PROGRESS: at 45.04% examples, 90911 words/s, in_qsize 5, out_

2021-02-23 17:44:36,749 : INFO : EPOCH 1 - PROGRESS: at 45.84% examples, 91070 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:37,856 : INFO : EPOCH 1 - PROGRESS: at 45.85% examples, 91072 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:38,943 : INFO : EPOCH 1 - PROGRESS: at 45.86% examples, 91075 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:40,035 : INFO : EPOCH 1 - PROGRESS: at 45.87% examples, 91077 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:41,151 : INFO : EPOCH 1 - PROGRESS: at 45.88% examples, 91079 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:42,278 : INFO : EPOCH 1 - PROGRESS: at 45.89% examples, 91080 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:43,386 : INFO : EPOCH 1 - PROGRESS: at 45.91% examples, 91083 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:44,488 : INFO : EPOCH 1 - PROGRESS: at 45.92% examples, 91086 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:44:45,588 : INFO : EPOCH 1 - PROGRESS: at 45.93% examples, 91089 words/s, in_qsize 5, out_

2021-02-23 17:45:57,387 : INFO : EPOCH 1 - PROGRESS: at 46.72% examples, 91256 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:45:58,405 : INFO : EPOCH 1 - PROGRESS: at 46.73% examples, 91261 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:45:59,513 : INFO : EPOCH 1 - PROGRESS: at 46.74% examples, 91263 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:00,621 : INFO : EPOCH 1 - PROGRESS: at 46.75% examples, 91265 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:01,695 : INFO : EPOCH 1 - PROGRESS: at 46.77% examples, 91268 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:02,812 : INFO : EPOCH 1 - PROGRESS: at 46.78% examples, 91270 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:03,906 : INFO : EPOCH 1 - PROGRESS: at 46.79% examples, 91273 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:05,016 : INFO : EPOCH 1 - PROGRESS: at 46.80% examples, 91274 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:46:06,082 : INFO : EPOCH 1 - PROGRESS: at 46.81% examples, 91277 words/s, in_qsize 5, out_

2021-02-23 17:47:17,666 : INFO : EPOCH 1 - PROGRESS: at 47.57% examples, 91428 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:18,702 : INFO : EPOCH 1 - PROGRESS: at 47.58% examples, 91429 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:19,749 : INFO : EPOCH 1 - PROGRESS: at 47.59% examples, 91430 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:20,881 : INFO : EPOCH 1 - PROGRESS: at 47.61% examples, 91430 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:21,967 : INFO : EPOCH 1 - PROGRESS: at 47.62% examples, 91433 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:23,046 : INFO : EPOCH 1 - PROGRESS: at 47.63% examples, 91435 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:47:24,135 : INFO : EPOCH 1 - PROGRESS: at 47.64% examples, 91438 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:25,241 : INFO : EPOCH 1 - PROGRESS: at 47.65% examples, 91439 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:47:26,322 : INFO : EPOCH 1 - PROGRESS: at 47.66% examples, 91442 words/s, in_qsize 5, out_

2021-02-23 17:48:37,929 : INFO : EPOCH 1 - PROGRESS: at 48.43% examples, 91581 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:39,037 : INFO : EPOCH 1 - PROGRESS: at 48.45% examples, 91583 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:40,124 : INFO : EPOCH 1 - PROGRESS: at 48.46% examples, 91585 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:41,157 : INFO : EPOCH 1 - PROGRESS: at 48.47% examples, 91589 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:42,259 : INFO : EPOCH 1 - PROGRESS: at 48.49% examples, 91592 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:43,295 : INFO : EPOCH 1 - PROGRESS: at 48.50% examples, 91596 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:44,338 : INFO : EPOCH 1 - PROGRESS: at 48.51% examples, 91597 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:45,401 : INFO : EPOCH 1 - PROGRESS: at 48.53% examples, 91597 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:48:46,472 : INFO : EPOCH 1 - PROGRESS: at 48.54% examples, 91600 words/s, in_qsize 5, out_

2021-02-23 17:49:57,384 : INFO : EPOCH 1 - PROGRESS: at 49.34% examples, 91733 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:49:58,519 : INFO : EPOCH 1 - PROGRESS: at 49.35% examples, 91734 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:49:59,598 : INFO : EPOCH 1 - PROGRESS: at 49.37% examples, 91736 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:00,700 : INFO : EPOCH 1 - PROGRESS: at 49.38% examples, 91738 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:01,793 : INFO : EPOCH 1 - PROGRESS: at 49.39% examples, 91742 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:02,810 : INFO : EPOCH 1 - PROGRESS: at 49.40% examples, 91744 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:03,823 : INFO : EPOCH 1 - PROGRESS: at 49.41% examples, 91745 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:04,933 : INFO : EPOCH 1 - PROGRESS: at 49.43% examples, 91747 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:50:05,942 : INFO : EPOCH 1 - PROGRESS: at 49.44% examples, 91748 words/s, in_qsize 5, out_

2021-02-23 17:51:16,899 : INFO : EPOCH 1 - PROGRESS: at 50.20% examples, 91858 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:17,955 : INFO : EPOCH 1 - PROGRESS: at 50.21% examples, 91861 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:19,035 : INFO : EPOCH 1 - PROGRESS: at 50.22% examples, 91863 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:20,070 : INFO : EPOCH 1 - PROGRESS: at 50.23% examples, 91867 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:21,154 : INFO : EPOCH 1 - PROGRESS: at 50.24% examples, 91866 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:51:22,247 : INFO : EPOCH 1 - PROGRESS: at 50.25% examples, 91868 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:23,335 : INFO : EPOCH 1 - PROGRESS: at 50.26% examples, 91870 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:51:24,410 : INFO : EPOCH 1 - PROGRESS: at 50.27% examples, 91871 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:51:25,537 : INFO : EPOCH 1 - PROGRESS: at 50.28% examples, 91873 words/s, in_qsize 5, out_

2021-02-23 17:52:36,437 : INFO : EPOCH 1 - PROGRESS: at 51.05% examples, 92004 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:37,546 : INFO : EPOCH 1 - PROGRESS: at 51.07% examples, 92005 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:38,620 : INFO : EPOCH 1 - PROGRESS: at 51.08% examples, 92008 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:39,665 : INFO : EPOCH 1 - PROGRESS: at 51.09% examples, 92012 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:40,741 : INFO : EPOCH 1 - PROGRESS: at 51.10% examples, 92014 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:41,835 : INFO : EPOCH 1 - PROGRESS: at 51.11% examples, 92015 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:42,901 : INFO : EPOCH 1 - PROGRESS: at 51.13% examples, 92018 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:43,983 : INFO : EPOCH 1 - PROGRESS: at 51.14% examples, 92021 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:52:45,040 : INFO : EPOCH 1 - PROGRESS: at 51.15% examples, 92024 words/s, in_qsize 5, out_

2021-02-23 17:53:56,042 : INFO : EPOCH 1 - PROGRESS: at 51.95% examples, 92156 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:53:57,135 : INFO : EPOCH 1 - PROGRESS: at 51.96% examples, 92158 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:53:58,226 : INFO : EPOCH 1 - PROGRESS: at 51.97% examples, 92160 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:53:59,322 : INFO : EPOCH 1 - PROGRESS: at 51.98% examples, 92161 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:54:00,436 : INFO : EPOCH 1 - PROGRESS: at 51.99% examples, 92162 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:54:01,532 : INFO : EPOCH 1 - PROGRESS: at 52.00% examples, 92164 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:54:02,579 : INFO : EPOCH 1 - PROGRESS: at 52.01% examples, 92167 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:54:03,663 : INFO : EPOCH 1 - PROGRESS: at 52.03% examples, 92169 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:54:04,754 : INFO : EPOCH 1 - PROGRESS: at 52.04% examples, 92170 words/s, in_qsize 5, out_

2021-02-23 17:55:16,578 : INFO : EPOCH 1 - PROGRESS: at 52.81% examples, 92256 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:17,670 : INFO : EPOCH 1 - PROGRESS: at 52.83% examples, 92257 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:18,737 : INFO : EPOCH 1 - PROGRESS: at 52.84% examples, 92259 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:19,874 : INFO : EPOCH 1 - PROGRESS: at 52.85% examples, 92259 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:20,991 : INFO : EPOCH 1 - PROGRESS: at 52.87% examples, 92260 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:22,102 : INFO : EPOCH 1 - PROGRESS: at 52.88% examples, 92262 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:23,238 : INFO : EPOCH 1 - PROGRESS: at 52.89% examples, 92263 words/s, in_qsize 4, out_qsize 1
2021-02-23 17:55:24,330 : INFO : EPOCH 1 - PROGRESS: at 52.90% examples, 92265 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:55:25,440 : INFO : EPOCH 1 - PROGRESS: at 52.91% examples, 92266 words/s, in_qsize 5, out_

2021-02-23 17:56:36,926 : INFO : EPOCH 1 - PROGRESS: at 54.14% examples, 92178 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:38,121 : INFO : EPOCH 1 - PROGRESS: at 54.16% examples, 92173 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:39,378 : INFO : EPOCH 1 - PROGRESS: at 54.19% examples, 92168 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:40,644 : INFO : EPOCH 1 - PROGRESS: at 54.22% examples, 92162 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:41,891 : INFO : EPOCH 1 - PROGRESS: at 54.25% examples, 92158 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:42,909 : INFO : EPOCH 1 - PROGRESS: at 54.27% examples, 92158 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:44,026 : INFO : EPOCH 1 - PROGRESS: at 54.30% examples, 92152 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:45,094 : INFO : EPOCH 1 - PROGRESS: at 54.32% examples, 92147 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:56:46,172 : INFO : EPOCH 1 - PROGRESS: at 54.35% examples, 92145 words/s, in_qsize 5, out_

2021-02-23 17:57:58,322 : INFO : EPOCH 1 - PROGRESS: at 55.91% examples, 91866 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:57:59,351 : INFO : EPOCH 1 - PROGRESS: at 55.93% examples, 91863 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:00,466 : INFO : EPOCH 1 - PROGRESS: at 55.95% examples, 91857 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:01,594 : INFO : EPOCH 1 - PROGRESS: at 55.97% examples, 91854 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:02,705 : INFO : EPOCH 1 - PROGRESS: at 56.00% examples, 91848 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:03,847 : INFO : EPOCH 1 - PROGRESS: at 56.02% examples, 91844 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:04,895 : INFO : EPOCH 1 - PROGRESS: at 56.05% examples, 91841 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:06,111 : INFO : EPOCH 1 - PROGRESS: at 56.07% examples, 91835 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:58:07,116 : INFO : EPOCH 1 - PROGRESS: at 56.09% examples, 91832 words/s, in_qsize 4, out_

2021-02-23 17:59:18,868 : INFO : EPOCH 1 - PROGRESS: at 57.55% examples, 91592 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:19,892 : INFO : EPOCH 1 - PROGRESS: at 57.57% examples, 91589 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:20,974 : INFO : EPOCH 1 - PROGRESS: at 57.59% examples, 91585 words/s, in_qsize 6, out_qsize 0
2021-02-23 17:59:22,013 : INFO : EPOCH 1 - PROGRESS: at 57.61% examples, 91581 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:23,083 : INFO : EPOCH 1 - PROGRESS: at 57.63% examples, 91577 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:24,141 : INFO : EPOCH 1 - PROGRESS: at 57.65% examples, 91573 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:25,216 : INFO : EPOCH 1 - PROGRESS: at 57.67% examples, 91569 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:26,305 : INFO : EPOCH 1 - PROGRESS: at 57.69% examples, 91564 words/s, in_qsize 5, out_qsize 0
2021-02-23 17:59:27,452 : INFO : EPOCH 1 - PROGRESS: at 57.72% examples, 91560 words/s, in_qsize 5, out_

2021-02-23 18:00:36,345 : INFO : EPOCH 1 - PROGRESS: at 60.04% examples, 91789 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:00:37,351 : INFO : EPOCH 1 - PROGRESS: at 60.07% examples, 91793 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:38,392 : INFO : EPOCH 1 - PROGRESS: at 60.11% examples, 91798 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:39,396 : INFO : EPOCH 1 - PROGRESS: at 60.14% examples, 91802 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:40,406 : INFO : EPOCH 1 - PROGRESS: at 60.18% examples, 91809 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:41,544 : INFO : EPOCH 1 - PROGRESS: at 60.22% examples, 91812 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:42,625 : INFO : EPOCH 1 - PROGRESS: at 60.26% examples, 91816 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:43,627 : INFO : EPOCH 1 - PROGRESS: at 60.30% examples, 91823 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:00:44,643 : INFO : EPOCH 1 - PROGRESS: at 60.33% examples, 91826 words/s, in_qsize 5, out_

2021-02-23 18:01:52,871 : INFO : EPOCH 1 - PROGRESS: at 62.70% examples, 92071 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:01:53,894 : INFO : EPOCH 1 - PROGRESS: at 62.73% examples, 92074 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:01:54,968 : INFO : EPOCH 1 - PROGRESS: at 62.79% examples, 92082 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:01:56,083 : INFO : EPOCH 1 - PROGRESS: at 62.84% examples, 92085 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:01:57,086 : INFO : EPOCH 1 - PROGRESS: at 62.89% examples, 92092 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:01:58,247 : INFO : EPOCH 1 - PROGRESS: at 62.92% examples, 92094 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:01:59,252 : INFO : EPOCH 1 - PROGRESS: at 62.97% examples, 92098 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:02:00,254 : INFO : EPOCH 1 - PROGRESS: at 63.01% examples, 92102 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:02:01,268 : INFO : EPOCH 1 - PROGRESS: at 63.05% examples, 92105 words/s, in_qsize 5, out_

2021-02-23 18:03:10,780 : INFO : EPOCH 1 - PROGRESS: at 66.34% examples, 92350 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:11,819 : INFO : EPOCH 1 - PROGRESS: at 66.40% examples, 92358 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:12,973 : INFO : EPOCH 1 - PROGRESS: at 66.45% examples, 92361 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:13,975 : INFO : EPOCH 1 - PROGRESS: at 66.51% examples, 92367 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:15,021 : INFO : EPOCH 1 - PROGRESS: at 66.56% examples, 92373 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:16,162 : INFO : EPOCH 1 - PROGRESS: at 66.61% examples, 92376 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:17,170 : INFO : EPOCH 1 - PROGRESS: at 66.66% examples, 92379 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:18,174 : INFO : EPOCH 1 - PROGRESS: at 66.71% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:03:19,204 : INFO : EPOCH 1 - PROGRESS: at 66.77% examples, 92389 words/s, in_qsize 5, out_

2021-02-23 18:04:29,002 : INFO : EPOCH 1 - PROGRESS: at 67.53% examples, 92403 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:30,020 : INFO : EPOCH 1 - PROGRESS: at 67.53% examples, 92402 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:31,043 : INFO : EPOCH 1 - PROGRESS: at 67.54% examples, 92400 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:32,199 : INFO : EPOCH 1 - PROGRESS: at 67.54% examples, 92398 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:33,315 : INFO : EPOCH 1 - PROGRESS: at 67.54% examples, 92396 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:04:34,327 : INFO : EPOCH 1 - PROGRESS: at 67.55% examples, 92397 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:35,513 : INFO : EPOCH 1 - PROGRESS: at 67.55% examples, 92394 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:36,560 : INFO : EPOCH 1 - PROGRESS: at 67.55% examples, 92394 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:04:37,636 : INFO : EPOCH 1 - PROGRESS: at 67.56% examples, 92392 words/s, in_qsize 5, out_

2021-02-23 18:05:47,567 : INFO : EPOCH 1 - PROGRESS: at 67.76% examples, 92320 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:48,650 : INFO : EPOCH 1 - PROGRESS: at 67.76% examples, 92318 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:05:49,671 : INFO : EPOCH 1 - PROGRESS: at 67.76% examples, 92316 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:50,769 : INFO : EPOCH 1 - PROGRESS: at 67.77% examples, 92315 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:51,828 : INFO : EPOCH 1 - PROGRESS: at 67.77% examples, 92314 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:52,848 : INFO : EPOCH 1 - PROGRESS: at 67.77% examples, 92314 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:53,873 : INFO : EPOCH 1 - PROGRESS: at 67.78% examples, 92312 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:54,907 : INFO : EPOCH 1 - PROGRESS: at 67.78% examples, 92312 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:05:55,923 : INFO : EPOCH 1 - PROGRESS: at 67.78% examples, 92312 words/s, in_qsize 5, out_

2021-02-23 18:07:05,802 : INFO : EPOCH 1 - PROGRESS: at 67.97% examples, 92237 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:06,915 : INFO : EPOCH 1 - PROGRESS: at 67.98% examples, 92236 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:07,921 : INFO : EPOCH 1 - PROGRESS: at 67.98% examples, 92235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:08,978 : INFO : EPOCH 1 - PROGRESS: at 67.98% examples, 92235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:10,060 : INFO : EPOCH 1 - PROGRESS: at 67.99% examples, 92234 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:11,151 : INFO : EPOCH 1 - PROGRESS: at 67.99% examples, 92233 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:12,237 : INFO : EPOCH 1 - PROGRESS: at 67.99% examples, 92232 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:13,329 : INFO : EPOCH 1 - PROGRESS: at 68.00% examples, 92230 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:07:14,348 : INFO : EPOCH 1 - PROGRESS: at 68.00% examples, 92231 words/s, in_qsize 6, out_

2021-02-23 18:08:25,217 : INFO : EPOCH 1 - PROGRESS: at 69.98% examples, 92004 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:08:26,506 : INFO : EPOCH 1 - PROGRESS: at 70.17% examples, 92001 words/s, in_qsize 5, out_qsize 1
2021-02-23 18:08:27,763 : INFO : EPOCH 1 - PROGRESS: at 70.35% examples, 91998 words/s, in_qsize 5, out_qsize 1
2021-02-23 18:08:29,021 : INFO : EPOCH 1 - PROGRESS: at 70.53% examples, 91995 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:08:30,053 : INFO : EPOCH 1 - PROGRESS: at 70.70% examples, 91996 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:08:31,263 : INFO : EPOCH 1 - PROGRESS: at 70.85% examples, 91989 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:08:32,287 : INFO : EPOCH 1 - PROGRESS: at 71.00% examples, 91990 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:08:33,353 : INFO : EPOCH 1 - PROGRESS: at 71.12% examples, 91987 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:08:34,466 : INFO : EPOCH 1 - PROGRESS: at 71.13% examples, 91988 words/s, in_qsize 5, out_

2021-02-23 18:09:45,845 : INFO : EPOCH 1 - PROGRESS: at 72.04% examples, 92073 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:46,950 : INFO : EPOCH 1 - PROGRESS: at 72.05% examples, 92074 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:48,085 : INFO : EPOCH 1 - PROGRESS: at 72.06% examples, 92074 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:49,154 : INFO : EPOCH 1 - PROGRESS: at 72.08% examples, 92076 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:50,242 : INFO : EPOCH 1 - PROGRESS: at 72.09% examples, 92077 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:51,373 : INFO : EPOCH 1 - PROGRESS: at 72.10% examples, 92078 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:52,472 : INFO : EPOCH 1 - PROGRESS: at 72.11% examples, 92078 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:53,579 : INFO : EPOCH 1 - PROGRESS: at 72.12% examples, 92079 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:09:54,647 : INFO : EPOCH 1 - PROGRESS: at 72.13% examples, 92081 words/s, in_qsize 5, out_

2021-02-23 18:11:05,201 : INFO : EPOCH 1 - PROGRESS: at 72.87% examples, 92160 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:06,313 : INFO : EPOCH 1 - PROGRESS: at 72.88% examples, 92161 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:07,371 : INFO : EPOCH 1 - PROGRESS: at 72.89% examples, 92162 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:08,449 : INFO : EPOCH 1 - PROGRESS: at 72.90% examples, 92164 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:09,494 : INFO : EPOCH 1 - PROGRESS: at 72.91% examples, 92166 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:10,509 : INFO : EPOCH 1 - PROGRESS: at 72.92% examples, 92166 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:11,612 : INFO : EPOCH 1 - PROGRESS: at 72.93% examples, 92167 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:12,706 : INFO : EPOCH 1 - PROGRESS: at 72.94% examples, 92167 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:11:13,789 : INFO : EPOCH 1 - PROGRESS: at 72.95% examples, 92169 words/s, in_qsize 5, out_

2021-02-23 18:12:25,509 : INFO : EPOCH 1 - PROGRESS: at 73.74% examples, 92233 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:26,662 : INFO : EPOCH 1 - PROGRESS: at 73.76% examples, 92233 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:27,785 : INFO : EPOCH 1 - PROGRESS: at 73.77% examples, 92234 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:28,868 : INFO : EPOCH 1 - PROGRESS: at 73.78% examples, 92235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:30,003 : INFO : EPOCH 1 - PROGRESS: at 73.79% examples, 92236 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:31,095 : INFO : EPOCH 1 - PROGRESS: at 73.80% examples, 92236 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:32,205 : INFO : EPOCH 1 - PROGRESS: at 73.81% examples, 92237 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:33,329 : INFO : EPOCH 1 - PROGRESS: at 73.83% examples, 92238 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:12:34,413 : INFO : EPOCH 1 - PROGRESS: at 73.84% examples, 92239 words/s, in_qsize 5, out_

2021-02-23 18:13:46,537 : INFO : EPOCH 1 - PROGRESS: at 74.63% examples, 92304 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:47,623 : INFO : EPOCH 1 - PROGRESS: at 74.64% examples, 92305 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:48,722 : INFO : EPOCH 1 - PROGRESS: at 74.65% examples, 92306 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:49,845 : INFO : EPOCH 1 - PROGRESS: at 74.66% examples, 92307 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:50,936 : INFO : EPOCH 1 - PROGRESS: at 74.68% examples, 92308 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:51,965 : INFO : EPOCH 1 - PROGRESS: at 74.69% examples, 92310 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:52,968 : INFO : EPOCH 1 - PROGRESS: at 74.70% examples, 92311 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:54,057 : INFO : EPOCH 1 - PROGRESS: at 74.71% examples, 92313 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:13:55,070 : INFO : EPOCH 1 - PROGRESS: at 74.72% examples, 92313 words/s, in_qsize 5, out_

2021-02-23 18:15:07,013 : INFO : EPOCH 1 - PROGRESS: at 75.50% examples, 92378 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:08,029 : INFO : EPOCH 1 - PROGRESS: at 75.52% examples, 92379 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:09,138 : INFO : EPOCH 1 - PROGRESS: at 75.53% examples, 92379 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:10,232 : INFO : EPOCH 1 - PROGRESS: at 75.54% examples, 92380 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:11,299 : INFO : EPOCH 1 - PROGRESS: at 75.55% examples, 92382 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:12,388 : INFO : EPOCH 1 - PROGRESS: at 75.56% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:13,481 : INFO : EPOCH 1 - PROGRESS: at 75.57% examples, 92384 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:14,523 : INFO : EPOCH 1 - PROGRESS: at 75.58% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:15:15,646 : INFO : EPOCH 1 - PROGRESS: at 75.60% examples, 92383 words/s, in_qsize 5, out_

2021-02-23 18:16:26,857 : INFO : EPOCH 1 - PROGRESS: at 76.38% examples, 92445 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:27,970 : INFO : EPOCH 1 - PROGRESS: at 76.39% examples, 92446 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:29,075 : INFO : EPOCH 1 - PROGRESS: at 76.40% examples, 92447 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:30,201 : INFO : EPOCH 1 - PROGRESS: at 76.41% examples, 92447 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:31,301 : INFO : EPOCH 1 - PROGRESS: at 76.43% examples, 92449 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:32,383 : INFO : EPOCH 1 - PROGRESS: at 76.44% examples, 92450 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:33,473 : INFO : EPOCH 1 - PROGRESS: at 76.45% examples, 92452 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:34,572 : INFO : EPOCH 1 - PROGRESS: at 76.46% examples, 92453 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:16:35,649 : INFO : EPOCH 1 - PROGRESS: at 76.48% examples, 92454 words/s, in_qsize 5, out_

2021-02-23 18:17:46,640 : INFO : EPOCH 1 - PROGRESS: at 77.53% examples, 92437 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:47,809 : INFO : EPOCH 1 - PROGRESS: at 77.55% examples, 92432 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:48,876 : INFO : EPOCH 1 - PROGRESS: at 77.57% examples, 92431 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:50,026 : INFO : EPOCH 1 - PROGRESS: at 77.60% examples, 92426 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:17:51,105 : INFO : EPOCH 1 - PROGRESS: at 77.62% examples, 92424 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:52,209 : INFO : EPOCH 1 - PROGRESS: at 77.65% examples, 92420 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:53,359 : INFO : EPOCH 1 - PROGRESS: at 77.67% examples, 92417 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:54,427 : INFO : EPOCH 1 - PROGRESS: at 77.69% examples, 92414 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:17:55,589 : INFO : EPOCH 1 - PROGRESS: at 77.72% examples, 92411 words/s, in_qsize 5, out_

2021-02-23 18:19:07,608 : INFO : EPOCH 1 - PROGRESS: at 79.34% examples, 92243 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:19:08,645 : INFO : EPOCH 1 - PROGRESS: at 79.36% examples, 92243 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:09,722 : INFO : EPOCH 1 - PROGRESS: at 79.39% examples, 92244 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:10,835 : INFO : EPOCH 1 - PROGRESS: at 79.42% examples, 92240 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:11,928 : INFO : EPOCH 1 - PROGRESS: at 79.44% examples, 92238 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:13,016 : INFO : EPOCH 1 - PROGRESS: at 79.47% examples, 92235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:14,073 : INFO : EPOCH 1 - PROGRESS: at 79.49% examples, 92234 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:19:15,241 : INFO : EPOCH 1 - PROGRESS: at 79.51% examples, 92229 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:19:16,292 : INFO : EPOCH 1 - PROGRESS: at 79.54% examples, 92228 words/s, in_qsize 5, out_

2021-02-23 18:20:29,171 : INFO : EPOCH 1 - PROGRESS: at 81.14% examples, 92052 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:30,266 : INFO : EPOCH 1 - PROGRESS: at 81.16% examples, 92049 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:31,385 : INFO : EPOCH 1 - PROGRESS: at 81.20% examples, 92049 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:32,465 : INFO : EPOCH 1 - PROGRESS: at 81.23% examples, 92048 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:33,490 : INFO : EPOCH 1 - PROGRESS: at 81.26% examples, 92048 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:34,618 : INFO : EPOCH 1 - PROGRESS: at 81.29% examples, 92044 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:35,622 : INFO : EPOCH 1 - PROGRESS: at 81.32% examples, 92044 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:36,798 : INFO : EPOCH 1 - PROGRESS: at 81.34% examples, 92038 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:20:37,833 : INFO : EPOCH 1 - PROGRESS: at 81.36% examples, 92038 words/s, in_qsize 5, out_

2021-02-23 18:21:50,378 : INFO : EPOCH 1 - PROGRESS: at 83.04% examples, 91873 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:51,649 : INFO : EPOCH 1 - PROGRESS: at 83.07% examples, 91870 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:52,910 : INFO : EPOCH 1 - PROGRESS: at 83.10% examples, 91866 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:54,146 : INFO : EPOCH 1 - PROGRESS: at 83.12% examples, 91863 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:55,199 : INFO : EPOCH 1 - PROGRESS: at 83.14% examples, 91863 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:56,337 : INFO : EPOCH 1 - PROGRESS: at 83.16% examples, 91858 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:57,441 : INFO : EPOCH 1 - PROGRESS: at 83.19% examples, 91856 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:58,532 : INFO : EPOCH 1 - PROGRESS: at 83.21% examples, 91853 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:21:59,710 : INFO : EPOCH 1 - PROGRESS: at 83.23% examples, 91850 words/s, in_qsize 5, out_

2021-02-23 18:23:11,350 : INFO : EPOCH 1 - PROGRESS: at 84.67% examples, 91673 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:12,560 : INFO : EPOCH 1 - PROGRESS: at 84.69% examples, 91669 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:13,616 : INFO : EPOCH 1 - PROGRESS: at 84.72% examples, 91669 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:14,710 : INFO : EPOCH 1 - PROGRESS: at 84.74% examples, 91665 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:15,877 : INFO : EPOCH 1 - PROGRESS: at 84.76% examples, 91662 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:16,937 : INFO : EPOCH 1 - PROGRESS: at 84.78% examples, 91659 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:18,122 : INFO : EPOCH 1 - PROGRESS: at 84.80% examples, 91656 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:19,123 : INFO : EPOCH 1 - PROGRESS: at 84.82% examples, 91654 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:23:20,390 : INFO : EPOCH 1 - PROGRESS: at 84.84% examples, 91649 words/s, in_qsize 4, out_

2021-02-23 18:24:30,797 : INFO : EPOCH 1 - PROGRESS: at 87.07% examples, 91767 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:31,805 : INFO : EPOCH 1 - PROGRESS: at 87.10% examples, 91769 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:32,817 : INFO : EPOCH 1 - PROGRESS: at 87.14% examples, 91772 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:33,832 : INFO : EPOCH 1 - PROGRESS: at 87.17% examples, 91774 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:34,836 : INFO : EPOCH 1 - PROGRESS: at 87.21% examples, 91777 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:35,843 : INFO : EPOCH 1 - PROGRESS: at 87.24% examples, 91780 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:36,862 : INFO : EPOCH 1 - PROGRESS: at 87.28% examples, 91784 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:37,863 : INFO : EPOCH 1 - PROGRESS: at 87.32% examples, 91787 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:24:38,911 : INFO : EPOCH 1 - PROGRESS: at 87.35% examples, 91791 words/s, in_qsize 5, out_

2021-02-23 18:25:47,208 : INFO : EPOCH 1 - PROGRESS: at 89.75% examples, 91957 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:25:48,217 : INFO : EPOCH 1 - PROGRESS: at 89.80% examples, 91962 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:25:49,339 : INFO : EPOCH 1 - PROGRESS: at 89.85% examples, 91964 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:25:50,459 : INFO : EPOCH 1 - PROGRESS: at 89.90% examples, 91966 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:25:51,460 : INFO : EPOCH 1 - PROGRESS: at 89.95% examples, 91971 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:25:52,472 : INFO : EPOCH 1 - PROGRESS: at 90.00% examples, 91974 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:25:53,482 : INFO : EPOCH 1 - PROGRESS: at 90.04% examples, 91976 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:25:54,502 : INFO : EPOCH 1 - PROGRESS: at 90.08% examples, 91979 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:25:55,641 : INFO : EPOCH 1 - PROGRESS: at 90.13% examples, 91981 words/s, in_qsize 5, out_

2021-02-23 18:27:05,551 : INFO : EPOCH 1 - PROGRESS: at 93.55% examples, 92180 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:06,572 : INFO : EPOCH 1 - PROGRESS: at 93.61% examples, 92184 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:07,631 : INFO : EPOCH 1 - PROGRESS: at 93.66% examples, 92187 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:08,847 : INFO : EPOCH 1 - PROGRESS: at 93.71% examples, 92188 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:09,930 : INFO : EPOCH 1 - PROGRESS: at 93.76% examples, 92189 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:10,959 : INFO : EPOCH 1 - PROGRESS: at 93.79% examples, 92192 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:11,984 : INFO : EPOCH 1 - PROGRESS: at 93.81% examples, 92194 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:13,007 : INFO : EPOCH 1 - PROGRESS: at 93.85% examples, 92197 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:27:14,039 : INFO : EPOCH 1 - PROGRESS: at 93.87% examples, 92199 words/s, in_qsize 5, out_

2021-02-23 18:28:24,144 : INFO : EPOCH 1 - PROGRESS: at 94.45% examples, 92180 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:25,220 : INFO : EPOCH 1 - PROGRESS: at 94.46% examples, 92178 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:26,292 : INFO : EPOCH 1 - PROGRESS: at 94.46% examples, 92177 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:27,396 : INFO : EPOCH 1 - PROGRESS: at 94.46% examples, 92177 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:28,472 : INFO : EPOCH 1 - PROGRESS: at 94.47% examples, 92176 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:29,500 : INFO : EPOCH 1 - PROGRESS: at 94.47% examples, 92175 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:30,652 : INFO : EPOCH 1 - PROGRESS: at 94.47% examples, 92173 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:31,766 : INFO : EPOCH 1 - PROGRESS: at 94.48% examples, 92172 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:28:32,806 : INFO : EPOCH 1 - PROGRESS: at 94.48% examples, 92171 words/s, in_qsize 5, out_

2021-02-23 18:29:44,059 : INFO : EPOCH 1 - PROGRESS: at 94.74% examples, 92111 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:45,187 : INFO : EPOCH 1 - PROGRESS: at 94.74% examples, 92109 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:46,332 : INFO : EPOCH 1 - PROGRESS: at 94.74% examples, 92108 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:47,490 : INFO : EPOCH 1 - PROGRESS: at 94.75% examples, 92105 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:48,513 : INFO : EPOCH 1 - PROGRESS: at 94.75% examples, 92105 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:49,585 : INFO : EPOCH 1 - PROGRESS: at 94.76% examples, 92105 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:50,747 : INFO : EPOCH 1 - PROGRESS: at 94.76% examples, 92102 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:51,759 : INFO : EPOCH 1 - PROGRESS: at 94.76% examples, 92103 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:29:52,810 : INFO : EPOCH 1 - PROGRESS: at 94.77% examples, 92101 words/s, in_qsize 5, out_

2021-02-23 18:31:03,353 : INFO : EPOCH 1 - PROGRESS: at 95.18% examples, 92002 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:04,386 : INFO : EPOCH 1 - PROGRESS: at 95.20% examples, 91999 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:31:05,394 : INFO : EPOCH 1 - PROGRESS: at 95.21% examples, 91996 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:06,401 : INFO : EPOCH 1 - PROGRESS: at 95.23% examples, 91993 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:07,455 : INFO : EPOCH 1 - PROGRESS: at 95.24% examples, 91991 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:08,471 : INFO : EPOCH 1 - PROGRESS: at 95.25% examples, 91988 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:09,482 : INFO : EPOCH 1 - PROGRESS: at 95.26% examples, 91985 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:10,492 : INFO : EPOCH 1 - PROGRESS: at 95.28% examples, 91983 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:31:11,596 : INFO : EPOCH 1 - PROGRESS: at 95.29% examples, 91980 words/s, in_qsize 5, out_

2021-02-23 18:32:22,139 : INFO : EPOCH 1 - PROGRESS: at 98.17% examples, 91936 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:23,170 : INFO : EPOCH 1 - PROGRESS: at 98.19% examples, 91936 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:24,259 : INFO : EPOCH 1 - PROGRESS: at 98.20% examples, 91936 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:25,332 : INFO : EPOCH 1 - PROGRESS: at 98.22% examples, 91937 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:26,441 : INFO : EPOCH 1 - PROGRESS: at 98.23% examples, 91938 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:27,547 : INFO : EPOCH 1 - PROGRESS: at 98.24% examples, 91938 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:28,602 : INFO : EPOCH 1 - PROGRESS: at 98.26% examples, 91940 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:29,676 : INFO : EPOCH 1 - PROGRESS: at 98.27% examples, 91940 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:32:30,788 : INFO : EPOCH 1 - PROGRESS: at 98.28% examples, 91941 words/s, in_qsize 5, out_

2021-02-23 18:33:42,662 : INFO : EPOCH 1 - PROGRESS: at 99.10% examples, 91994 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:43,745 : INFO : EPOCH 1 - PROGRESS: at 99.11% examples, 91995 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:44,864 : INFO : EPOCH 1 - PROGRESS: at 99.13% examples, 91995 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:45,947 : INFO : EPOCH 1 - PROGRESS: at 99.14% examples, 91997 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:47,008 : INFO : EPOCH 1 - PROGRESS: at 99.15% examples, 91998 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:48,015 : INFO : EPOCH 1 - PROGRESS: at 99.16% examples, 91998 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:49,082 : INFO : EPOCH 1 - PROGRESS: at 99.17% examples, 91999 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:50,208 : INFO : EPOCH 1 - PROGRESS: at 99.18% examples, 91999 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:33:51,359 : INFO : EPOCH 1 - PROGRESS: at 99.19% examples, 91999 words/s, in_qsize 5, out_

2021-02-23 18:35:02,371 : INFO : worker thread finished; awaiting finish of 2 more threads
2021-02-23 18:35:02,393 : INFO : worker thread finished; awaiting finish of 1 more threads
2021-02-23 18:35:02,394 : INFO : worker thread finished; awaiting finish of 0 more threads
2021-02-23 18:35:02,395 : INFO : EPOCH - 1 : training on 534796798 raw words (476073678 effective words) took 5172.1s, 92046 effective words/s
2021-02-23 18:35:03,455 : INFO : EPOCH 2 - PROGRESS: at 0.01% examples, 82854 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:35:04,516 : INFO : EPOCH 2 - PROGRESS: at 0.02% examples, 91113 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:35:05,608 : INFO : EPOCH 2 - PROGRESS: at 0.04% examples, 93287 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:35:06,703 : INFO : EPOCH 2 - PROGRESS: at 0.05% examples, 94084 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:35:07,773 : INFO : EPOCH 2 - PROGRESS: at 0.06% examples, 94853 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:35:08,816 : INF

2021-02-23 18:36:20,027 : INFO : EPOCH 2 - PROGRESS: at 0.82% examples, 96291 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:21,130 : INFO : EPOCH 2 - PROGRESS: at 0.84% examples, 96248 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:22,227 : INFO : EPOCH 2 - PROGRESS: at 0.85% examples, 96235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:23,280 : INFO : EPOCH 2 - PROGRESS: at 0.86% examples, 96273 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:24,362 : INFO : EPOCH 2 - PROGRESS: at 0.87% examples, 96294 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:25,429 : INFO : EPOCH 2 - PROGRESS: at 0.88% examples, 96311 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:26,458 : INFO : EPOCH 2 - PROGRESS: at 0.89% examples, 96280 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:27,579 : INFO : EPOCH 2 - PROGRESS: at 0.91% examples, 96243 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:36:28,645 : INFO : EPOCH 2 - PROGRESS: at 0.92% examples, 96260 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:37:40,534 : INFO : EPOCH 2 - PROGRESS: at 1.74% examples, 95546 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:41,635 : INFO : EPOCH 2 - PROGRESS: at 1.76% examples, 95466 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:42,693 : INFO : EPOCH 2 - PROGRESS: at 1.79% examples, 95364 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:43,770 : INFO : EPOCH 2 - PROGRESS: at 1.81% examples, 95306 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:44,813 : INFO : EPOCH 2 - PROGRESS: at 1.84% examples, 95217 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:45,903 : INFO : EPOCH 2 - PROGRESS: at 1.86% examples, 95147 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:46,952 : INFO : EPOCH 2 - PROGRESS: at 1.88% examples, 95052 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:48,041 : INFO : EPOCH 2 - PROGRESS: at 1.91% examples, 94990 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:37:49,081 : INFO : EPOCH 2 - PROGRESS: at 1.93% examples, 94903 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:39:01,088 : INFO : EPOCH 2 - PROGRESS: at 3.59% examples, 90942 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:02,257 : INFO : EPOCH 2 - PROGRESS: at 3.61% examples, 90854 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:03,264 : INFO : EPOCH 2 - PROGRESS: at 3.64% examples, 90861 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:39:04,414 : INFO : EPOCH 2 - PROGRESS: at 3.66% examples, 90778 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:05,452 : INFO : EPOCH 2 - PROGRESS: at 3.69% examples, 90741 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:06,600 : INFO : EPOCH 2 - PROGRESS: at 3.71% examples, 90694 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:07,605 : INFO : EPOCH 2 - PROGRESS: at 3.73% examples, 90664 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:08,776 : INFO : EPOCH 2 - PROGRESS: at 3.76% examples, 90612 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:39:09,781 : INFO : EPOCH 2 - PROGRESS: at 3.78% examples, 90589 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:40:23,066 : INFO : EPOCH 2 - PROGRESS: at 5.38% examples, 88398 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:24,095 : INFO : EPOCH 2 - PROGRESS: at 5.40% examples, 88407 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:25,278 : INFO : EPOCH 2 - PROGRESS: at 5.43% examples, 88348 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:26,538 : INFO : EPOCH 2 - PROGRESS: at 5.45% examples, 88317 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:27,785 : INFO : EPOCH 2 - PROGRESS: at 5.48% examples, 88294 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:28,800 : INFO : EPOCH 2 - PROGRESS: at 5.51% examples, 88279 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:40:29,937 : INFO : EPOCH 2 - PROGRESS: at 5.53% examples, 88256 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:30,973 : INFO : EPOCH 2 - PROGRESS: at 5.55% examples, 88235 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:40:32,117 : INFO : EPOCH 2 - PROGRESS: at 5.58% examples, 88213 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:41:45,188 : INFO : EPOCH 2 - PROGRESS: at 7.14% examples, 86865 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:46,198 : INFO : EPOCH 2 - PROGRESS: at 7.16% examples, 86860 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:47,367 : INFO : EPOCH 2 - PROGRESS: at 7.19% examples, 86820 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:48,477 : INFO : EPOCH 2 - PROGRESS: at 7.21% examples, 86813 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:49,592 : INFO : EPOCH 2 - PROGRESS: at 7.24% examples, 86783 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:50,602 : INFO : EPOCH 2 - PROGRESS: at 7.26% examples, 86776 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:51,655 : INFO : EPOCH 2 - PROGRESS: at 7.28% examples, 86760 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:52,761 : INFO : EPOCH 2 - PROGRESS: at 7.30% examples, 86734 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:41:53,812 : INFO : EPOCH 2 - PROGRESS: at 7.32% examples, 86719 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:43:05,903 : INFO : EPOCH 2 - PROGRESS: at 8.87% examples, 85730 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:07,062 : INFO : EPOCH 2 - PROGRESS: at 8.90% examples, 85701 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:08,160 : INFO : EPOCH 2 - PROGRESS: at 8.92% examples, 85703 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:09,275 : INFO : EPOCH 2 - PROGRESS: at 8.95% examples, 85684 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:10,406 : INFO : EPOCH 2 - PROGRESS: at 8.97% examples, 85678 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:11,494 : INFO : EPOCH 2 - PROGRESS: at 9.00% examples, 85663 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:12,651 : INFO : EPOCH 2 - PROGRESS: at 9.03% examples, 85654 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:13,690 : INFO : EPOCH 2 - PROGRESS: at 9.05% examples, 85648 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:43:14,908 : INFO : EPOCH 2 - PROGRESS: at 9.08% examples, 85628 words/s, in_qsize 5, out_qsize 0
2

2021-02-23 18:44:28,906 : INFO : EPOCH 2 - PROGRESS: at 10.65% examples, 84962 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:29,982 : INFO : EPOCH 2 - PROGRESS: at 10.67% examples, 84952 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:31,116 : INFO : EPOCH 2 - PROGRESS: at 10.69% examples, 84944 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:32,222 : INFO : EPOCH 2 - PROGRESS: at 10.71% examples, 84929 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:33,311 : INFO : EPOCH 2 - PROGRESS: at 10.74% examples, 84932 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:34,456 : INFO : EPOCH 2 - PROGRESS: at 10.76% examples, 84910 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:35,534 : INFO : EPOCH 2 - PROGRESS: at 10.78% examples, 84914 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:36,672 : INFO : EPOCH 2 - PROGRESS: at 10.80% examples, 84894 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:44:37,715 : INFO : EPOCH 2 - PROGRESS: at 10.83% examples, 84888 words/s, in_qsize 5, out_

2021-02-23 18:45:50,243 : INFO : EPOCH 2 - PROGRESS: at 12.24% examples, 84368 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:51,310 : INFO : EPOCH 2 - PROGRESS: at 12.26% examples, 84361 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:45:52,481 : INFO : EPOCH 2 - PROGRESS: at 12.29% examples, 84353 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:53,485 : INFO : EPOCH 2 - PROGRESS: at 12.31% examples, 84354 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:54,568 : INFO : EPOCH 2 - PROGRESS: at 12.33% examples, 84344 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:55,673 : INFO : EPOCH 2 - PROGRESS: at 12.35% examples, 84333 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:56,827 : INFO : EPOCH 2 - PROGRESS: at 12.37% examples, 84329 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:57,893 : INFO : EPOCH 2 - PROGRESS: at 12.39% examples, 84322 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:45:59,096 : INFO : EPOCH 2 - PROGRESS: at 12.41% examples, 84309 words/s, in_qsize 5, out_

2021-02-23 18:47:11,115 : INFO : EPOCH 2 - PROGRESS: at 13.80% examples, 83951 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:12,167 : INFO : EPOCH 2 - PROGRESS: at 13.82% examples, 83944 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:13,319 : INFO : EPOCH 2 - PROGRESS: at 13.84% examples, 83939 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:14,367 : INFO : EPOCH 2 - PROGRESS: at 13.86% examples, 83935 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:15,488 : INFO : EPOCH 2 - PROGRESS: at 13.88% examples, 83934 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:16,595 : INFO : EPOCH 2 - PROGRESS: at 13.91% examples, 83924 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:17,702 : INFO : EPOCH 2 - PROGRESS: at 13.93% examples, 83925 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:18,826 : INFO : EPOCH 2 - PROGRESS: at 13.95% examples, 83912 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:47:19,834 : INFO : EPOCH 2 - PROGRESS: at 13.97% examples, 83923 words/s, in_qsize 5, out_

2021-02-23 18:48:30,324 : INFO : EPOCH 2 - PROGRESS: at 16.05% examples, 84986 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:31,333 : INFO : EPOCH 2 - PROGRESS: at 16.09% examples, 85010 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:48:32,357 : INFO : EPOCH 2 - PROGRESS: at 16.13% examples, 85041 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:33,362 : INFO : EPOCH 2 - PROGRESS: at 16.16% examples, 85065 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:34,462 : INFO : EPOCH 2 - PROGRESS: at 16.20% examples, 85088 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:35,597 : INFO : EPOCH 2 - PROGRESS: at 16.24% examples, 85109 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:36,598 : INFO : EPOCH 2 - PROGRESS: at 16.29% examples, 85144 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:48:37,619 : INFO : EPOCH 2 - PROGRESS: at 16.32% examples, 85155 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:48:38,636 : INFO : EPOCH 2 - PROGRESS: at 16.35% examples, 85187 words/s, in_qsize 4, out_

2021-02-23 18:49:47,265 : INFO : EPOCH 2 - PROGRESS: at 18.78% examples, 86689 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:48,273 : INFO : EPOCH 2 - PROGRESS: at 18.82% examples, 86708 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:49,281 : INFO : EPOCH 2 - PROGRESS: at 18.85% examples, 86727 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:50,289 : INFO : EPOCH 2 - PROGRESS: at 18.89% examples, 86756 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:51,328 : INFO : EPOCH 2 - PROGRESS: at 18.93% examples, 86782 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:52,333 : INFO : EPOCH 2 - PROGRESS: at 18.96% examples, 86801 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:53,342 : INFO : EPOCH 2 - PROGRESS: at 19.00% examples, 86820 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:54,352 : INFO : EPOCH 2 - PROGRESS: at 19.03% examples, 86838 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:49:55,358 : INFO : EPOCH 2 - PROGRESS: at 19.07% examples, 86857 words/s, in_qsize 5, out_

2021-02-23 18:51:04,628 : INFO : EPOCH 2 - PROGRESS: at 21.52% examples, 88158 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:05,631 : INFO : EPOCH 2 - PROGRESS: at 21.56% examples, 88183 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:06,731 : INFO : EPOCH 2 - PROGRESS: at 21.60% examples, 88201 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:07,825 : INFO : EPOCH 2 - PROGRESS: at 21.64% examples, 88218 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:08,846 : INFO : EPOCH 2 - PROGRESS: at 21.68% examples, 88242 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:09,988 : INFO : EPOCH 2 - PROGRESS: at 21.72% examples, 88256 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:11,058 : INFO : EPOCH 2 - PROGRESS: at 21.76% examples, 88275 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:51:12,066 : INFO : EPOCH 2 - PROGRESS: at 21.80% examples, 88291 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:51:13,075 : INFO : EPOCH 2 - PROGRESS: at 21.84% examples, 88316 words/s, in_qsize 5, out_

2021-02-23 18:52:21,926 : INFO : EPOCH 2 - PROGRESS: at 24.27% examples, 89368 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:22,981 : INFO : EPOCH 2 - PROGRESS: at 24.32% examples, 89387 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:24,126 : INFO : EPOCH 2 - PROGRESS: at 24.38% examples, 89407 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:25,186 : INFO : EPOCH 2 - PROGRESS: at 24.43% examples, 89426 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:26,195 : INFO : EPOCH 2 - PROGRESS: at 24.48% examples, 89449 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:27,312 : INFO : EPOCH 2 - PROGRESS: at 24.53% examples, 89463 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:28,314 : INFO : EPOCH 2 - PROGRESS: at 24.57% examples, 89478 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:29,345 : INFO : EPOCH 2 - PROGRESS: at 24.61% examples, 89490 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:52:30,411 : INFO : EPOCH 2 - PROGRESS: at 24.66% examples, 89507 words/s, in_qsize 5, out_

2021-02-23 18:53:40,911 : INFO : EPOCH 2 - PROGRESS: at 28.22% examples, 90632 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:41,957 : INFO : EPOCH 2 - PROGRESS: at 28.27% examples, 90649 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:53:42,970 : INFO : EPOCH 2 - PROGRESS: at 28.32% examples, 90661 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:43,993 : INFO : EPOCH 2 - PROGRESS: at 28.38% examples, 90681 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:45,018 : INFO : EPOCH 2 - PROGRESS: at 28.43% examples, 90699 words/s, in_qsize 6, out_qsize 0
2021-02-23 18:53:46,173 : INFO : EPOCH 2 - PROGRESS: at 28.49% examples, 90708 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:47,173 : INFO : EPOCH 2 - PROGRESS: at 28.54% examples, 90729 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:48,191 : INFO : EPOCH 2 - PROGRESS: at 28.60% examples, 90748 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:53:49,370 : INFO : EPOCH 2 - PROGRESS: at 28.65% examples, 90754 words/s, in_qsize 5, out_

2021-02-23 18:54:59,450 : INFO : EPOCH 2 - PROGRESS: at 32.27% examples, 91737 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:00,546 : INFO : EPOCH 2 - PROGRESS: at 32.32% examples, 91749 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:01,654 : INFO : EPOCH 2 - PROGRESS: at 32.38% examples, 91759 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:02,700 : INFO : EPOCH 2 - PROGRESS: at 32.44% examples, 91782 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:03,840 : INFO : EPOCH 2 - PROGRESS: at 32.49% examples, 91790 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:04,869 : INFO : EPOCH 2 - PROGRESS: at 32.55% examples, 91806 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:05,877 : INFO : EPOCH 2 - PROGRESS: at 32.60% examples, 91818 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:06,994 : INFO : EPOCH 2 - PROGRESS: at 32.66% examples, 91834 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:55:08,092 : INFO : EPOCH 2 - PROGRESS: at 32.72% examples, 91845 words/s, in_qsize 5, out_

2021-02-23 18:56:17,177 : INFO : EPOCH 2 - PROGRESS: at 35.10% examples, 92463 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:18,238 : INFO : EPOCH 2 - PROGRESS: at 35.10% examples, 92454 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:19,372 : INFO : EPOCH 2 - PROGRESS: at 35.10% examples, 92448 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:56:20,390 : INFO : EPOCH 2 - PROGRESS: at 35.11% examples, 92449 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:21,414 : INFO : EPOCH 2 - PROGRESS: at 35.11% examples, 92452 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:22,446 : INFO : EPOCH 2 - PROGRESS: at 35.11% examples, 92440 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:23,513 : INFO : EPOCH 2 - PROGRESS: at 35.12% examples, 92439 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:24,572 : INFO : EPOCH 2 - PROGRESS: at 35.12% examples, 92437 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:56:25,598 : INFO : EPOCH 2 - PROGRESS: at 35.12% examples, 92432 words/s, in_qsize 5, out_

2021-02-23 18:57:35,272 : INFO : EPOCH 2 - PROGRESS: at 35.33% examples, 92231 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:36,368 : INFO : EPOCH 2 - PROGRESS: at 35.34% examples, 92226 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:37,471 : INFO : EPOCH 2 - PROGRESS: at 35.34% examples, 92222 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:38,607 : INFO : EPOCH 2 - PROGRESS: at 35.34% examples, 92218 words/s, in_qsize 4, out_qsize 1
2021-02-23 18:57:39,718 : INFO : EPOCH 2 - PROGRESS: at 35.35% examples, 92215 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:40,740 : INFO : EPOCH 2 - PROGRESS: at 35.35% examples, 92217 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:41,751 : INFO : EPOCH 2 - PROGRESS: at 35.36% examples, 92208 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:42,811 : INFO : EPOCH 2 - PROGRESS: at 35.36% examples, 92205 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:57:43,954 : INFO : EPOCH 2 - PROGRESS: at 35.36% examples, 92198 words/s, in_qsize 5, out_

2021-02-23 18:58:54,497 : INFO : EPOCH 2 - PROGRESS: at 35.62% examples, 91943 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:58:55,563 : INFO : EPOCH 2 - PROGRESS: at 35.62% examples, 91941 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:58:56,605 : INFO : EPOCH 2 - PROGRESS: at 35.63% examples, 91940 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:58:57,719 : INFO : EPOCH 2 - PROGRESS: at 35.63% examples, 91934 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:58:58,839 : INFO : EPOCH 2 - PROGRESS: at 35.63% examples, 91930 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:58:59,876 : INFO : EPOCH 2 - PROGRESS: at 35.64% examples, 91926 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:59:00,991 : INFO : EPOCH 2 - PROGRESS: at 35.64% examples, 91923 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:59:01,993 : INFO : EPOCH 2 - PROGRESS: at 35.65% examples, 91926 words/s, in_qsize 5, out_qsize 0
2021-02-23 18:59:03,021 : INFO : EPOCH 2 - PROGRESS: at 35.65% examples, 91923 words/s, in_qsize 5, out_

2021-02-23 19:00:13,197 : INFO : EPOCH 2 - PROGRESS: at 35.86% examples, 91758 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:14,260 : INFO : EPOCH 2 - PROGRESS: at 35.87% examples, 91756 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:15,346 : INFO : EPOCH 2 - PROGRESS: at 35.87% examples, 91753 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:16,358 : INFO : EPOCH 2 - PROGRESS: at 35.87% examples, 91752 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:17,401 : INFO : EPOCH 2 - PROGRESS: at 35.88% examples, 91750 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:18,438 : INFO : EPOCH 2 - PROGRESS: at 35.88% examples, 91747 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:19,493 : INFO : EPOCH 2 - PROGRESS: at 35.88% examples, 91746 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:20,506 : INFO : EPOCH 2 - PROGRESS: at 35.89% examples, 91741 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:00:21,605 : INFO : EPOCH 2 - PROGRESS: at 35.89% examples, 91740 words/s, in_qsize 5, out_

2021-02-23 19:01:32,355 : INFO : EPOCH 2 - PROGRESS: at 36.09% examples, 91629 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:33,539 : INFO : EPOCH 2 - PROGRESS: at 36.10% examples, 91626 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:34,611 : INFO : EPOCH 2 - PROGRESS: at 36.10% examples, 91624 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:35,688 : INFO : EPOCH 2 - PROGRESS: at 36.10% examples, 91622 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:36,727 : INFO : EPOCH 2 - PROGRESS: at 36.10% examples, 91622 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:37,838 : INFO : EPOCH 2 - PROGRESS: at 36.11% examples, 91619 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:38,939 : INFO : EPOCH 2 - PROGRESS: at 36.11% examples, 91618 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:39,949 : INFO : EPOCH 2 - PROGRESS: at 36.11% examples, 91618 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:01:40,985 : INFO : EPOCH 2 - PROGRESS: at 36.12% examples, 91618 words/s, in_qsize 5, out_

2021-02-23 19:02:50,985 : INFO : EPOCH 2 - PROGRESS: at 36.31% examples, 91510 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:52,032 : INFO : EPOCH 2 - PROGRESS: at 36.31% examples, 91507 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:53,044 : INFO : EPOCH 2 - PROGRESS: at 36.31% examples, 91510 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:54,123 : INFO : EPOCH 2 - PROGRESS: at 36.32% examples, 91502 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:02:55,140 : INFO : EPOCH 2 - PROGRESS: at 36.32% examples, 91504 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:56,182 : INFO : EPOCH 2 - PROGRESS: at 36.32% examples, 91501 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:57,263 : INFO : EPOCH 2 - PROGRESS: at 36.32% examples, 91499 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:58,388 : INFO : EPOCH 2 - PROGRESS: at 36.33% examples, 91498 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:02:59,526 : INFO : EPOCH 2 - PROGRESS: at 36.33% examples, 91494 words/s, in_qsize 5, out_

2021-02-23 19:04:09,603 : INFO : EPOCH 2 - PROGRESS: at 36.84% examples, 91204 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:10,637 : INFO : EPOCH 2 - PROGRESS: at 36.85% examples, 91195 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:11,678 : INFO : EPOCH 2 - PROGRESS: at 36.86% examples, 91185 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:12,734 : INFO : EPOCH 2 - PROGRESS: at 36.88% examples, 91174 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:13,788 : INFO : EPOCH 2 - PROGRESS: at 36.89% examples, 91164 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:14,854 : INFO : EPOCH 2 - PROGRESS: at 36.91% examples, 91153 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:04:15,897 : INFO : EPOCH 2 - PROGRESS: at 36.92% examples, 91143 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:04:16,934 : INFO : EPOCH 2 - PROGRESS: at 36.93% examples, 91134 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:04:17,986 : INFO : EPOCH 2 - PROGRESS: at 36.95% examples, 91124 words/s, in_qsize 4, out_

2021-02-23 19:05:26,555 : INFO : EPOCH 2 - PROGRESS: at 39.24% examples, 90631 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:05:27,792 : INFO : EPOCH 2 - PROGRESS: at 39.39% examples, 90618 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:05:28,801 : INFO : EPOCH 2 - PROGRESS: at 39.54% examples, 90612 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:05:29,872 : INFO : EPOCH 2 - PROGRESS: at 39.72% examples, 90612 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:05:31,121 : INFO : EPOCH 2 - PROGRESS: at 39.88% examples, 90599 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:05:32,126 : INFO : EPOCH 2 - PROGRESS: at 40.03% examples, 90597 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:05:33,128 : INFO : EPOCH 2 - PROGRESS: at 40.18% examples, 90592 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:05:34,152 : INFO : EPOCH 2 - PROGRESS: at 40.33% examples, 90589 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:05:35,370 : INFO : EPOCH 2 - PROGRESS: at 40.49% examples, 90577 words/s, in_qsize 5, out_

2021-02-23 19:06:47,673 : INFO : EPOCH 2 - PROGRESS: at 43.33% examples, 90655 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:48,743 : INFO : EPOCH 2 - PROGRESS: at 43.34% examples, 90659 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:49,828 : INFO : EPOCH 2 - PROGRESS: at 43.35% examples, 90663 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:50,924 : INFO : EPOCH 2 - PROGRESS: at 43.36% examples, 90667 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:52,036 : INFO : EPOCH 2 - PROGRESS: at 43.38% examples, 90670 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:53,125 : INFO : EPOCH 2 - PROGRESS: at 43.39% examples, 90673 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:54,170 : INFO : EPOCH 2 - PROGRESS: at 43.40% examples, 90678 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:55,248 : INFO : EPOCH 2 - PROGRESS: at 43.41% examples, 90682 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:06:56,308 : INFO : EPOCH 2 - PROGRESS: at 43.42% examples, 90685 words/s, in_qsize 5, out_

2021-02-23 19:08:07,726 : INFO : EPOCH 2 - PROGRESS: at 44.17% examples, 90869 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:08,860 : INFO : EPOCH 2 - PROGRESS: at 44.18% examples, 90871 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:09,968 : INFO : EPOCH 2 - PROGRESS: at 44.20% examples, 90873 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:11,074 : INFO : EPOCH 2 - PROGRESS: at 44.21% examples, 90874 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:12,175 : INFO : EPOCH 2 - PROGRESS: at 44.22% examples, 90876 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:13,305 : INFO : EPOCH 2 - PROGRESS: at 44.23% examples, 90878 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:14,420 : INFO : EPOCH 2 - PROGRESS: at 44.24% examples, 90880 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:08:15,530 : INFO : EPOCH 2 - PROGRESS: at 44.25% examples, 90882 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:08:16,608 : INFO : EPOCH 2 - PROGRESS: at 44.26% examples, 90885 words/s, in_qsize 5, out_

2021-02-23 19:09:27,815 : INFO : EPOCH 2 - PROGRESS: at 44.98% examples, 91059 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:28,929 : INFO : EPOCH 2 - PROGRESS: at 44.99% examples, 91061 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:29,983 : INFO : EPOCH 2 - PROGRESS: at 45.00% examples, 91065 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:31,104 : INFO : EPOCH 2 - PROGRESS: at 45.01% examples, 91066 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:09:32,193 : INFO : EPOCH 2 - PROGRESS: at 45.02% examples, 91069 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:33,302 : INFO : EPOCH 2 - PROGRESS: at 45.04% examples, 91072 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:34,382 : INFO : EPOCH 2 - PROGRESS: at 45.05% examples, 91075 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:35,449 : INFO : EPOCH 2 - PROGRESS: at 45.06% examples, 91078 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:09:36,530 : INFO : EPOCH 2 - PROGRESS: at 45.07% examples, 91081 words/s, in_qsize 5, out_

2021-02-23 19:10:48,123 : INFO : EPOCH 2 - PROGRESS: at 45.87% examples, 91246 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:49,234 : INFO : EPOCH 2 - PROGRESS: at 45.88% examples, 91248 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:50,359 : INFO : EPOCH 2 - PROGRESS: at 45.89% examples, 91250 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:51,494 : INFO : EPOCH 2 - PROGRESS: at 45.91% examples, 91251 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:52,595 : INFO : EPOCH 2 - PROGRESS: at 45.92% examples, 91254 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:53,698 : INFO : EPOCH 2 - PROGRESS: at 45.93% examples, 91257 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:54,797 : INFO : EPOCH 2 - PROGRESS: at 45.94% examples, 91259 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:55,896 : INFO : EPOCH 2 - PROGRESS: at 45.95% examples, 91261 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:10:56,980 : INFO : EPOCH 2 - PROGRESS: at 45.97% examples, 91264 words/s, in_qsize 5, out_

2021-02-23 19:12:07,624 : INFO : EPOCH 2 - PROGRESS: at 46.75% examples, 91450 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:08,625 : INFO : EPOCH 2 - PROGRESS: at 46.76% examples, 91452 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:09,628 : INFO : EPOCH 2 - PROGRESS: at 46.77% examples, 91454 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:10,742 : INFO : EPOCH 2 - PROGRESS: at 46.78% examples, 91456 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:11,817 : INFO : EPOCH 2 - PROGRESS: at 46.80% examples, 91458 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:12,919 : INFO : EPOCH 2 - PROGRESS: at 46.81% examples, 91461 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:14,014 : INFO : EPOCH 2 - PROGRESS: at 46.82% examples, 91463 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:15,107 : INFO : EPOCH 2 - PROGRESS: at 46.83% examples, 91465 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:12:16,177 : INFO : EPOCH 2 - PROGRESS: at 46.84% examples, 91468 words/s, in_qsize 5, out_

2021-02-23 19:13:27,447 : INFO : EPOCH 2 - PROGRESS: at 47.60% examples, 91619 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:28,525 : INFO : EPOCH 2 - PROGRESS: at 47.61% examples, 91622 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:29,562 : INFO : EPOCH 2 - PROGRESS: at 47.62% examples, 91626 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:30,633 : INFO : EPOCH 2 - PROGRESS: at 47.64% examples, 91629 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:31,722 : INFO : EPOCH 2 - PROGRESS: at 47.65% examples, 91631 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:32,755 : INFO : EPOCH 2 - PROGRESS: at 47.66% examples, 91632 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:33,825 : INFO : EPOCH 2 - PROGRESS: at 47.67% examples, 91635 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:34,900 : INFO : EPOCH 2 - PROGRESS: at 47.68% examples, 91637 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:13:35,912 : INFO : EPOCH 2 - PROGRESS: at 47.69% examples, 91640 words/s, in_qsize 5, out_

2021-02-23 19:14:47,328 : INFO : EPOCH 2 - PROGRESS: at 48.46% examples, 91773 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:48,376 : INFO : EPOCH 2 - PROGRESS: at 48.47% examples, 91776 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:49,480 : INFO : EPOCH 2 - PROGRESS: at 48.49% examples, 91779 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:50,530 : INFO : EPOCH 2 - PROGRESS: at 48.50% examples, 91782 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:51,616 : INFO : EPOCH 2 - PROGRESS: at 48.51% examples, 91785 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:52,667 : INFO : EPOCH 2 - PROGRESS: at 48.53% examples, 91786 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:53,789 : INFO : EPOCH 2 - PROGRESS: at 48.54% examples, 91787 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:54,887 : INFO : EPOCH 2 - PROGRESS: at 48.55% examples, 91789 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:14:55,972 : INFO : EPOCH 2 - PROGRESS: at 48.57% examples, 91792 words/s, in_qsize 5, out_

2021-02-23 19:16:07,922 : INFO : EPOCH 2 - PROGRESS: at 49.38% examples, 91919 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:08,993 : INFO : EPOCH 2 - PROGRESS: at 49.39% examples, 91924 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:10,026 : INFO : EPOCH 2 - PROGRESS: at 49.40% examples, 91925 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:11,159 : INFO : EPOCH 2 - PROGRESS: at 49.41% examples, 91925 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:12,298 : INFO : EPOCH 2 - PROGRESS: at 49.43% examples, 91926 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:16:13,386 : INFO : EPOCH 2 - PROGRESS: at 49.44% examples, 91928 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:14,490 : INFO : EPOCH 2 - PROGRESS: at 49.45% examples, 91930 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:15,553 : INFO : EPOCH 2 - PROGRESS: at 49.47% examples, 91933 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:16:16,630 : INFO : EPOCH 2 - PROGRESS: at 49.48% examples, 91936 words/s, in_qsize 5, out_

2021-02-23 19:17:28,111 : INFO : EPOCH 2 - PROGRESS: at 50.24% examples, 92062 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:17:29,186 : INFO : EPOCH 2 - PROGRESS: at 50.25% examples, 92064 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:30,241 : INFO : EPOCH 2 - PROGRESS: at 50.26% examples, 92066 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:31,314 : INFO : EPOCH 2 - PROGRESS: at 50.27% examples, 92069 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:32,418 : INFO : EPOCH 2 - PROGRESS: at 50.28% examples, 92070 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:33,487 : INFO : EPOCH 2 - PROGRESS: at 50.29% examples, 92073 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:34,604 : INFO : EPOCH 2 - PROGRESS: at 50.31% examples, 92074 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:35,674 : INFO : EPOCH 2 - PROGRESS: at 50.32% examples, 92075 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:17:36,789 : INFO : EPOCH 2 - PROGRESS: at 50.33% examples, 92077 words/s, in_qsize 5, out_

2021-02-23 19:18:48,176 : INFO : EPOCH 2 - PROGRESS: at 51.11% examples, 92197 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:49,274 : INFO : EPOCH 2 - PROGRESS: at 51.12% examples, 92198 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:50,374 : INFO : EPOCH 2 - PROGRESS: at 51.13% examples, 92200 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:51,471 : INFO : EPOCH 2 - PROGRESS: at 51.15% examples, 92202 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:52,523 : INFO : EPOCH 2 - PROGRESS: at 51.16% examples, 92205 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:53,606 : INFO : EPOCH 2 - PROGRESS: at 51.17% examples, 92207 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:54,658 : INFO : EPOCH 2 - PROGRESS: at 51.18% examples, 92208 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:55,663 : INFO : EPOCH 2 - PROGRESS: at 51.20% examples, 92210 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:18:56,779 : INFO : EPOCH 2 - PROGRESS: at 51.21% examples, 92212 words/s, in_qsize 5, out_

2021-02-23 19:20:07,591 : INFO : EPOCH 2 - PROGRESS: at 51.99% examples, 92325 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:20:08,623 : INFO : EPOCH 2 - PROGRESS: at 52.00% examples, 92328 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:09,706 : INFO : EPOCH 2 - PROGRESS: at 52.01% examples, 92330 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:10,805 : INFO : EPOCH 2 - PROGRESS: at 52.02% examples, 92331 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:11,878 : INFO : EPOCH 2 - PROGRESS: at 52.04% examples, 92333 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:12,942 : INFO : EPOCH 2 - PROGRESS: at 52.05% examples, 92336 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:14,008 : INFO : EPOCH 2 - PROGRESS: at 52.06% examples, 92338 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:15,077 : INFO : EPOCH 2 - PROGRESS: at 52.07% examples, 92340 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:20:16,083 : INFO : EPOCH 2 - PROGRESS: at 52.08% examples, 92341 words/s, in_qsize 5, out_

2021-02-23 19:21:27,714 : INFO : EPOCH 2 - PROGRESS: at 52.86% examples, 92432 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:28,841 : INFO : EPOCH 2 - PROGRESS: at 52.87% examples, 92433 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:29,943 : INFO : EPOCH 2 - PROGRESS: at 52.89% examples, 92435 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:31,042 : INFO : EPOCH 2 - PROGRESS: at 52.90% examples, 92437 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:32,145 : INFO : EPOCH 2 - PROGRESS: at 52.91% examples, 92439 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:33,166 : INFO : EPOCH 2 - PROGRESS: at 52.93% examples, 92436 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:34,198 : INFO : EPOCH 2 - PROGRESS: at 52.95% examples, 92435 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:35,252 : INFO : EPOCH 2 - PROGRESS: at 52.97% examples, 92430 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:21:36,256 : INFO : EPOCH 2 - PROGRESS: at 53.00% examples, 92427 words/s, in_qsize 5, out_

2021-02-23 19:22:49,280 : INFO : EPOCH 2 - PROGRESS: at 54.27% examples, 92336 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:22:50,288 : INFO : EPOCH 2 - PROGRESS: at 54.29% examples, 92337 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:51,434 : INFO : EPOCH 2 - PROGRESS: at 54.32% examples, 92329 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:52,453 : INFO : EPOCH 2 - PROGRESS: at 54.34% examples, 92326 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:53,604 : INFO : EPOCH 2 - PROGRESS: at 54.37% examples, 92322 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:54,655 : INFO : EPOCH 2 - PROGRESS: at 54.39% examples, 92317 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:55,748 : INFO : EPOCH 2 - PROGRESS: at 54.42% examples, 92315 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:56,820 : INFO : EPOCH 2 - PROGRESS: at 54.44% examples, 92309 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:22:57,858 : INFO : EPOCH 2 - PROGRESS: at 54.47% examples, 92308 words/s, in_qsize 5, out_

2021-02-23 19:24:10,635 : INFO : EPOCH 2 - PROGRESS: at 56.04% examples, 92030 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:11,768 : INFO : EPOCH 2 - PROGRESS: at 56.06% examples, 92024 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:12,823 : INFO : EPOCH 2 - PROGRESS: at 56.08% examples, 92020 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:13,949 : INFO : EPOCH 2 - PROGRESS: at 56.11% examples, 92016 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:15,029 : INFO : EPOCH 2 - PROGRESS: at 56.13% examples, 92012 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:16,044 : INFO : EPOCH 2 - PROGRESS: at 56.15% examples, 92009 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:17,187 : INFO : EPOCH 2 - PROGRESS: at 56.17% examples, 92002 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:18,292 : INFO : EPOCH 2 - PROGRESS: at 56.19% examples, 91999 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:24:19,441 : INFO : EPOCH 2 - PROGRESS: at 56.21% examples, 91992 words/s, in_qsize 5, out_

2021-02-23 19:25:31,641 : INFO : EPOCH 2 - PROGRESS: at 57.68% examples, 91752 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:32,654 : INFO : EPOCH 2 - PROGRESS: at 57.70% examples, 91752 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:33,790 : INFO : EPOCH 2 - PROGRESS: at 57.73% examples, 91746 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:34,798 : INFO : EPOCH 2 - PROGRESS: at 57.76% examples, 91752 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:35,859 : INFO : EPOCH 2 - PROGRESS: at 57.80% examples, 91757 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:36,882 : INFO : EPOCH 2 - PROGRESS: at 57.83% examples, 91761 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:37,971 : INFO : EPOCH 2 - PROGRESS: at 57.87% examples, 91765 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:39,130 : INFO : EPOCH 2 - PROGRESS: at 57.92% examples, 91770 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:25:40,173 : INFO : EPOCH 2 - PROGRESS: at 57.94% examples, 91770 words/s, in_qsize 5, out_

2021-02-23 19:26:48,683 : INFO : EPOCH 2 - PROGRESS: at 60.26% examples, 92000 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:49,703 : INFO : EPOCH 2 - PROGRESS: at 60.30% examples, 92007 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:50,708 : INFO : EPOCH 2 - PROGRESS: at 60.34% examples, 92011 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:51,833 : INFO : EPOCH 2 - PROGRESS: at 60.38% examples, 92014 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:52,844 : INFO : EPOCH 2 - PROGRESS: at 60.41% examples, 92018 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:53,883 : INFO : EPOCH 2 - PROGRESS: at 60.45% examples, 92023 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:54,912 : INFO : EPOCH 2 - PROGRESS: at 60.49% examples, 92029 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:26:55,924 : INFO : EPOCH 2 - PROGRESS: at 60.53% examples, 92033 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:26:56,937 : INFO : EPOCH 2 - PROGRESS: at 60.56% examples, 92037 words/s, in_qsize 5, out_

2021-02-23 19:28:05,932 : INFO : EPOCH 2 - PROGRESS: at 63.01% examples, 92287 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:06,933 : INFO : EPOCH 2 - PROGRESS: at 63.05% examples, 92291 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:07,939 : INFO : EPOCH 2 - PROGRESS: at 63.09% examples, 92295 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:09,105 : INFO : EPOCH 2 - PROGRESS: at 63.14% examples, 92297 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:28:10,106 : INFO : EPOCH 2 - PROGRESS: at 63.19% examples, 92304 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:11,153 : INFO : EPOCH 2 - PROGRESS: at 63.24% examples, 92309 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:12,305 : INFO : EPOCH 2 - PROGRESS: at 63.29% examples, 92312 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:13,422 : INFO : EPOCH 2 - PROGRESS: at 63.34% examples, 92312 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:28:14,450 : INFO : EPOCH 2 - PROGRESS: at 63.36% examples, 92312 words/s, in_qsize 5, out_

2021-02-23 19:29:26,287 : INFO : EPOCH 2 - PROGRESS: at 66.85% examples, 92590 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:27,335 : INFO : EPOCH 2 - PROGRESS: at 66.89% examples, 92596 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:28,337 : INFO : EPOCH 2 - PROGRESS: at 66.92% examples, 92600 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:29,368 : INFO : EPOCH 2 - PROGRESS: at 66.96% examples, 92606 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:30,376 : INFO : EPOCH 2 - PROGRESS: at 67.00% examples, 92610 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:31,388 : INFO : EPOCH 2 - PROGRESS: at 67.02% examples, 92611 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:32,475 : INFO : EPOCH 2 - PROGRESS: at 67.04% examples, 92613 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:29:33,514 : INFO : EPOCH 2 - PROGRESS: at 67.06% examples, 92616 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:29:34,571 : INFO : EPOCH 2 - PROGRESS: at 67.08% examples, 92619 words/s, in_qsize 5, out_

2021-02-23 19:30:44,731 : INFO : EPOCH 2 - PROGRESS: at 67.56% examples, 92583 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:45,758 : INFO : EPOCH 2 - PROGRESS: at 67.57% examples, 92580 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:46,859 : INFO : EPOCH 2 - PROGRESS: at 67.57% examples, 92578 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:47,965 : INFO : EPOCH 2 - PROGRESS: at 67.57% examples, 92577 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:49,037 : INFO : EPOCH 2 - PROGRESS: at 67.58% examples, 92576 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:50,060 : INFO : EPOCH 2 - PROGRESS: at 67.58% examples, 92576 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:51,079 : INFO : EPOCH 2 - PROGRESS: at 67.59% examples, 92574 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:52,111 : INFO : EPOCH 2 - PROGRESS: at 67.59% examples, 92573 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:30:53,187 : INFO : EPOCH 2 - PROGRESS: at 67.59% examples, 92572 words/s, in_qsize 5, out_

2021-02-23 19:32:03,419 : INFO : EPOCH 2 - PROGRESS: at 67.79% examples, 92505 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:04,523 : INFO : EPOCH 2 - PROGRESS: at 67.79% examples, 92502 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:05,560 : INFO : EPOCH 2 - PROGRESS: at 67.79% examples, 92502 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:06,749 : INFO : EPOCH 2 - PROGRESS: at 67.80% examples, 92499 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:07,791 : INFO : EPOCH 2 - PROGRESS: at 67.80% examples, 92500 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:08,794 : INFO : EPOCH 2 - PROGRESS: at 67.80% examples, 92500 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:09,800 : INFO : EPOCH 2 - PROGRESS: at 67.81% examples, 92498 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:10,862 : INFO : EPOCH 2 - PROGRESS: at 67.81% examples, 92497 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:32:11,905 : INFO : EPOCH 2 - PROGRESS: at 67.81% examples, 92496 words/s, in_qsize 5, out_

2021-02-23 19:33:22,096 : INFO : EPOCH 2 - PROGRESS: at 68.01% examples, 92426 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:23,172 : INFO : EPOCH 2 - PROGRESS: at 68.01% examples, 92425 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:24,243 : INFO : EPOCH 2 - PROGRESS: at 68.01% examples, 92425 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:25,317 : INFO : EPOCH 2 - PROGRESS: at 68.02% examples, 92424 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:26,348 : INFO : EPOCH 2 - PROGRESS: at 68.02% examples, 92423 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:27,378 : INFO : EPOCH 2 - PROGRESS: at 68.02% examples, 92423 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:28,396 : INFO : EPOCH 2 - PROGRESS: at 68.03% examples, 92420 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:29,500 : INFO : EPOCH 2 - PROGRESS: at 68.03% examples, 92419 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:33:30,627 : INFO : EPOCH 2 - PROGRESS: at 68.04% examples, 92418 words/s, in_qsize 5, out_

2021-02-23 19:34:39,937 : INFO : EPOCH 2 - PROGRESS: at 71.14% examples, 92170 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:40,990 : INFO : EPOCH 2 - PROGRESS: at 71.15% examples, 92169 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:42,082 : INFO : EPOCH 2 - PROGRESS: at 71.16% examples, 92168 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:43,185 : INFO : EPOCH 2 - PROGRESS: at 71.19% examples, 92169 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:44,302 : INFO : EPOCH 2 - PROGRESS: at 71.21% examples, 92170 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:45,424 : INFO : EPOCH 2 - PROGRESS: at 71.26% examples, 92171 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:46,534 : INFO : EPOCH 2 - PROGRESS: at 71.30% examples, 92172 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:47,625 : INFO : EPOCH 2 - PROGRESS: at 71.32% examples, 92174 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:34:48,632 : INFO : EPOCH 2 - PROGRESS: at 71.33% examples, 92175 words/s, in_qsize 5, out_

2021-02-23 19:36:00,309 : INFO : EPOCH 2 - PROGRESS: at 72.13% examples, 92247 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:01,423 : INFO : EPOCH 2 - PROGRESS: at 72.14% examples, 92248 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:02,531 : INFO : EPOCH 2 - PROGRESS: at 72.15% examples, 92248 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:03,573 : INFO : EPOCH 2 - PROGRESS: at 72.16% examples, 92251 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:04,648 : INFO : EPOCH 2 - PROGRESS: at 72.18% examples, 92252 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:05,669 : INFO : EPOCH 2 - PROGRESS: at 72.19% examples, 92253 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:06,775 : INFO : EPOCH 2 - PROGRESS: at 72.20% examples, 92254 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:07,856 : INFO : EPOCH 2 - PROGRESS: at 72.21% examples, 92254 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:36:08,966 : INFO : EPOCH 2 - PROGRESS: at 72.22% examples, 92255 words/s, in_qsize 5, out_

2021-02-23 19:37:19,596 : INFO : EPOCH 2 - PROGRESS: at 72.95% examples, 92323 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:20,611 : INFO : EPOCH 2 - PROGRESS: at 72.96% examples, 92323 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:21,611 : INFO : EPOCH 2 - PROGRESS: at 72.97% examples, 92324 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:22,699 : INFO : EPOCH 2 - PROGRESS: at 72.98% examples, 92325 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:23,781 : INFO : EPOCH 2 - PROGRESS: at 72.99% examples, 92326 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:24,815 : INFO : EPOCH 2 - PROGRESS: at 73.00% examples, 92326 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:25,912 : INFO : EPOCH 2 - PROGRESS: at 73.01% examples, 92327 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:27,035 : INFO : EPOCH 2 - PROGRESS: at 73.03% examples, 92327 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:37:28,157 : INFO : EPOCH 2 - PROGRESS: at 73.04% examples, 92327 words/s, in_qsize 5, out_

2021-02-23 19:38:40,002 : INFO : EPOCH 2 - PROGRESS: at 73.83% examples, 92382 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:41,106 : INFO : EPOCH 2 - PROGRESS: at 73.84% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:42,143 : INFO : EPOCH 2 - PROGRESS: at 73.85% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:43,260 : INFO : EPOCH 2 - PROGRESS: at 73.87% examples, 92383 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:44,376 : INFO : EPOCH 2 - PROGRESS: at 73.88% examples, 92384 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:45,461 : INFO : EPOCH 2 - PROGRESS: at 73.89% examples, 92385 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:46,565 : INFO : EPOCH 2 - PROGRESS: at 73.90% examples, 92386 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:47,651 : INFO : EPOCH 2 - PROGRESS: at 73.91% examples, 92388 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:38:48,675 : INFO : EPOCH 2 - PROGRESS: at 73.92% examples, 92388 words/s, in_qsize 5, out_

2021-02-23 19:40:00,377 : INFO : EPOCH 2 - PROGRESS: at 74.71% examples, 92449 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:01,461 : INFO : EPOCH 2 - PROGRESS: at 74.73% examples, 92450 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:02,540 : INFO : EPOCH 2 - PROGRESS: at 74.74% examples, 92451 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:03,659 : INFO : EPOCH 2 - PROGRESS: at 74.75% examples, 92452 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:04,775 : INFO : EPOCH 2 - PROGRESS: at 74.76% examples, 92453 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:05,784 : INFO : EPOCH 2 - PROGRESS: at 74.77% examples, 92454 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:06,872 : INFO : EPOCH 2 - PROGRESS: at 74.78% examples, 92455 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:07,967 : INFO : EPOCH 2 - PROGRESS: at 74.79% examples, 92456 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:40:08,971 : INFO : EPOCH 2 - PROGRESS: at 74.81% examples, 92457 words/s, in_qsize 5, out_

2021-02-23 19:41:21,422 : INFO : EPOCH 2 - PROGRESS: at 75.58% examples, 92502 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:22,550 : INFO : EPOCH 2 - PROGRESS: at 75.60% examples, 92503 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:23,673 : INFO : EPOCH 2 - PROGRESS: at 75.61% examples, 92503 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:24,773 : INFO : EPOCH 2 - PROGRESS: at 75.62% examples, 92504 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:25,887 : INFO : EPOCH 2 - PROGRESS: at 75.63% examples, 92505 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:26,968 : INFO : EPOCH 2 - PROGRESS: at 75.64% examples, 92506 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:28,064 : INFO : EPOCH 2 - PROGRESS: at 75.65% examples, 92507 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:29,146 : INFO : EPOCH 2 - PROGRESS: at 75.67% examples, 92508 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:41:30,247 : INFO : EPOCH 2 - PROGRESS: at 75.68% examples, 92510 words/s, in_qsize 5, out_

2021-02-23 19:42:41,508 : INFO : EPOCH 2 - PROGRESS: at 76.46% examples, 92572 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:42:42,652 : INFO : EPOCH 2 - PROGRESS: at 76.48% examples, 92572 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:42:43,776 : INFO : EPOCH 2 - PROGRESS: at 76.49% examples, 92572 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:42:44,885 : INFO : EPOCH 2 - PROGRESS: at 76.50% examples, 92573 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:42:45,986 : INFO : EPOCH 2 - PROGRESS: at 76.51% examples, 92574 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:42:47,074 : INFO : EPOCH 2 - PROGRESS: at 76.53% examples, 92575 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:42:48,195 : INFO : EPOCH 2 - PROGRESS: at 76.54% examples, 92576 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:42:49,301 : INFO : EPOCH 2 - PROGRESS: at 76.55% examples, 92576 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:42:50,373 : INFO : EPOCH 2 - PROGRESS: at 76.57% examples, 92578 words/s, in_qsize 5, out_

2021-02-23 19:44:01,950 : INFO : EPOCH 2 - PROGRESS: at 77.70% examples, 92521 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:03,034 : INFO : EPOCH 2 - PROGRESS: at 77.73% examples, 92518 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:04,124 : INFO : EPOCH 2 - PROGRESS: at 77.75% examples, 92514 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:05,235 : INFO : EPOCH 2 - PROGRESS: at 77.77% examples, 92512 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:06,327 : INFO : EPOCH 2 - PROGRESS: at 77.80% examples, 92508 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:07,397 : INFO : EPOCH 2 - PROGRESS: at 77.82% examples, 92506 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:08,502 : INFO : EPOCH 2 - PROGRESS: at 77.84% examples, 92502 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:09,529 : INFO : EPOCH 2 - PROGRESS: at 77.86% examples, 92500 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:44:10,544 : INFO : EPOCH 2 - PROGRESS: at 77.89% examples, 92497 words/s, in_qsize 5, out_

2021-02-23 19:45:23,729 : INFO : EPOCH 2 - PROGRESS: at 79.53% examples, 92325 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:24,906 : INFO : EPOCH 2 - PROGRESS: at 79.57% examples, 92323 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:26,077 : INFO : EPOCH 2 - PROGRESS: at 79.60% examples, 92322 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:27,082 : INFO : EPOCH 2 - PROGRESS: at 79.62% examples, 92320 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:28,137 : INFO : EPOCH 2 - PROGRESS: at 79.64% examples, 92317 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:29,185 : INFO : EPOCH 2 - PROGRESS: at 79.66% examples, 92314 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:30,379 : INFO : EPOCH 2 - PROGRESS: at 79.69% examples, 92310 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:31,411 : INFO : EPOCH 2 - PROGRESS: at 79.71% examples, 92310 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:45:32,554 : INFO : EPOCH 2 - PROGRESS: at 79.74% examples, 92305 words/s, in_qsize 5, out_

2021-02-23 19:46:45,483 : INFO : EPOCH 2 - PROGRESS: at 81.35% examples, 92122 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:46,547 : INFO : EPOCH 2 - PROGRESS: at 81.38% examples, 92119 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:47,587 : INFO : EPOCH 2 - PROGRESS: at 81.40% examples, 92116 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:48,657 : INFO : EPOCH 2 - PROGRESS: at 81.43% examples, 92116 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:49,718 : INFO : EPOCH 2 - PROGRESS: at 81.46% examples, 92113 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:50,751 : INFO : EPOCH 2 - PROGRESS: at 81.48% examples, 92110 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:51,780 : INFO : EPOCH 2 - PROGRESS: at 81.50% examples, 92108 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:52,853 : INFO : EPOCH 2 - PROGRESS: at 81.52% examples, 92105 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:46:53,893 : INFO : EPOCH 2 - PROGRESS: at 81.54% examples, 92102 words/s, in_qsize 5, out_

2021-02-23 19:48:05,350 : INFO : EPOCH 2 - PROGRESS: at 83.18% examples, 91931 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:06,459 : INFO : EPOCH 2 - PROGRESS: at 83.20% examples, 91929 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:07,559 : INFO : EPOCH 2 - PROGRESS: at 83.22% examples, 91926 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:08,587 : INFO : EPOCH 2 - PROGRESS: at 83.24% examples, 91924 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:09,637 : INFO : EPOCH 2 - PROGRESS: at 83.26% examples, 91921 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:10,683 : INFO : EPOCH 2 - PROGRESS: at 83.28% examples, 91919 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:11,787 : INFO : EPOCH 2 - PROGRESS: at 83.30% examples, 91915 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:12,794 : INFO : EPOCH 2 - PROGRESS: at 83.32% examples, 91913 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:48:13,814 : INFO : EPOCH 2 - PROGRESS: at 83.34% examples, 91911 words/s, in_qsize 5, out_

2021-02-23 19:49:27,826 : INFO : EPOCH 2 - PROGRESS: at 84.82% examples, 91723 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:28,991 : INFO : EPOCH 2 - PROGRESS: at 84.84% examples, 91720 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:30,050 : INFO : EPOCH 2 - PROGRESS: at 84.86% examples, 91717 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:31,221 : INFO : EPOCH 2 - PROGRESS: at 84.89% examples, 91714 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:32,305 : INFO : EPOCH 2 - PROGRESS: at 84.91% examples, 91713 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:33,459 : INFO : EPOCH 2 - PROGRESS: at 84.93% examples, 91708 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:34,506 : INFO : EPOCH 2 - PROGRESS: at 84.96% examples, 91708 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:35,677 : INFO : EPOCH 2 - PROGRESS: at 84.98% examples, 91703 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:49:36,716 : INFO : EPOCH 2 - PROGRESS: at 85.00% examples, 91702 words/s, in_qsize 5, out_

2021-02-23 19:50:47,124 : INFO : EPOCH 2 - PROGRESS: at 87.33% examples, 91851 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:50:48,135 : INFO : EPOCH 2 - PROGRESS: at 87.36% examples, 91853 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:49,145 : INFO : EPOCH 2 - PROGRESS: at 87.40% examples, 91858 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:50,153 : INFO : EPOCH 2 - PROGRESS: at 87.44% examples, 91862 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:51,308 : INFO : EPOCH 2 - PROGRESS: at 87.47% examples, 91864 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:52,365 : INFO : EPOCH 2 - PROGRESS: at 87.51% examples, 91867 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:53,368 : INFO : EPOCH 2 - PROGRESS: at 87.55% examples, 91872 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:54,368 : INFO : EPOCH 2 - PROGRESS: at 87.58% examples, 91873 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:50:55,373 : INFO : EPOCH 2 - PROGRESS: at 87.62% examples, 91875 words/s, in_qsize 5, out_

2021-02-23 19:52:03,809 : INFO : EPOCH 2 - PROGRESS: at 90.14% examples, 92063 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:04,943 : INFO : EPOCH 2 - PROGRESS: at 90.19% examples, 92066 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:05,989 : INFO : EPOCH 2 - PROGRESS: at 90.25% examples, 92069 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:07,011 : INFO : EPOCH 2 - PROGRESS: at 90.30% examples, 92074 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:08,159 : INFO : EPOCH 2 - PROGRESS: at 90.36% examples, 92076 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:09,172 : INFO : EPOCH 2 - PROGRESS: at 90.42% examples, 92080 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:10,183 : INFO : EPOCH 2 - PROGRESS: at 90.47% examples, 92085 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:11,372 : INFO : EPOCH 2 - PROGRESS: at 90.53% examples, 92086 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:52:12,374 : INFO : EPOCH 2 - PROGRESS: at 90.58% examples, 92090 words/s, in_qsize 4, out_

2021-02-23 19:53:22,768 : INFO : EPOCH 2 - PROGRESS: at 93.88% examples, 92281 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:23,781 : INFO : EPOCH 2 - PROGRESS: at 93.90% examples, 92282 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:24,781 : INFO : EPOCH 2 - PROGRESS: at 93.91% examples, 92283 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:25,848 : INFO : EPOCH 2 - PROGRESS: at 93.94% examples, 92284 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:26,871 : INFO : EPOCH 2 - PROGRESS: at 93.98% examples, 92289 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:27,893 : INFO : EPOCH 2 - PROGRESS: at 94.02% examples, 92291 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:28,913 : INFO : EPOCH 2 - PROGRESS: at 94.06% examples, 92294 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:53:29,925 : INFO : EPOCH 2 - PROGRESS: at 94.10% examples, 92298 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:53:31,024 : INFO : EPOCH 2 - PROGRESS: at 94.15% examples, 92301 words/s, in_qsize 5, out_

2021-02-23 19:54:40,784 : INFO : EPOCH 2 - PROGRESS: at 94.48% examples, 92262 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:41,793 : INFO : EPOCH 2 - PROGRESS: at 94.48% examples, 92261 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:42,908 : INFO : EPOCH 2 - PROGRESS: at 94.49% examples, 92260 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:43,969 : INFO : EPOCH 2 - PROGRESS: at 94.49% examples, 92259 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:44,969 : INFO : EPOCH 2 - PROGRESS: at 94.49% examples, 92258 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:54:46,007 : INFO : EPOCH 2 - PROGRESS: at 94.50% examples, 92257 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:47,088 : INFO : EPOCH 2 - PROGRESS: at 94.50% examples, 92256 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:48,164 : INFO : EPOCH 2 - PROGRESS: at 94.50% examples, 92255 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:54:49,240 : INFO : EPOCH 2 - PROGRESS: at 94.51% examples, 92255 words/s, in_qsize 5, out_

2021-02-23 19:56:00,268 : INFO : EPOCH 2 - PROGRESS: at 94.77% examples, 92194 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:01,430 : INFO : EPOCH 2 - PROGRESS: at 94.77% examples, 92191 words/s, in_qsize 4, out_qsize 1
2021-02-23 19:56:02,478 : INFO : EPOCH 2 - PROGRESS: at 94.78% examples, 92192 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:03,525 : INFO : EPOCH 2 - PROGRESS: at 94.78% examples, 92192 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:04,634 : INFO : EPOCH 2 - PROGRESS: at 94.78% examples, 92190 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:05,757 : INFO : EPOCH 2 - PROGRESS: at 94.79% examples, 92189 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:06,906 : INFO : EPOCH 2 - PROGRESS: at 94.79% examples, 92188 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:08,002 : INFO : EPOCH 2 - PROGRESS: at 94.79% examples, 92187 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:56:09,003 : INFO : EPOCH 2 - PROGRESS: at 94.80% examples, 92186 words/s, in_qsize 6, out_

2021-02-23 19:57:18,806 : INFO : EPOCH 2 - PROGRESS: at 95.29% examples, 92068 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:19,839 : INFO : EPOCH 2 - PROGRESS: at 95.30% examples, 92064 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:20,882 : INFO : EPOCH 2 - PROGRESS: at 95.31% examples, 92061 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:21,921 : INFO : EPOCH 2 - PROGRESS: at 95.32% examples, 92057 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:22,982 : INFO : EPOCH 2 - PROGRESS: at 95.33% examples, 92054 words/s, in_qsize 6, out_qsize 1
2021-02-23 19:57:23,999 : INFO : EPOCH 2 - PROGRESS: at 95.35% examples, 92052 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:25,004 : INFO : EPOCH 2 - PROGRESS: at 95.36% examples, 92048 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:26,011 : INFO : EPOCH 2 - PROGRESS: at 95.37% examples, 92045 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:57:27,051 : INFO : EPOCH 2 - PROGRESS: at 95.38% examples, 92042 words/s, in_qsize 5, out_

2021-02-23 19:58:38,414 : INFO : EPOCH 2 - PROGRESS: at 98.28% examples, 92009 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:58:39,454 : INFO : EPOCH 2 - PROGRESS: at 98.29% examples, 92011 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:40,460 : INFO : EPOCH 2 - PROGRESS: at 98.30% examples, 92012 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:41,549 : INFO : EPOCH 2 - PROGRESS: at 98.31% examples, 92012 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:42,628 : INFO : EPOCH 2 - PROGRESS: at 98.32% examples, 92013 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:43,713 : INFO : EPOCH 2 - PROGRESS: at 98.34% examples, 92014 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:44,763 : INFO : EPOCH 2 - PROGRESS: at 98.35% examples, 92015 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:45,845 : INFO : EPOCH 2 - PROGRESS: at 98.36% examples, 92017 words/s, in_qsize 5, out_qsize 0
2021-02-23 19:58:46,932 : INFO : EPOCH 2 - PROGRESS: at 98.38% examples, 92018 words/s, in_qsize 5, out_

2021-02-23 19:59:58,394 : INFO : EPOCH 2 - PROGRESS: at 99.18% examples, 92070 words/s, in_qsize 6, out_qsize 0
2021-02-23 19:59:59,453 : INFO : EPOCH 2 - PROGRESS: at 99.19% examples, 92070 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:00,563 : INFO : EPOCH 2 - PROGRESS: at 99.20% examples, 92071 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:01,673 : INFO : EPOCH 2 - PROGRESS: at 99.21% examples, 92071 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:02,804 : INFO : EPOCH 2 - PROGRESS: at 99.23% examples, 92071 words/s, in_qsize 4, out_qsize 1
2021-02-23 20:00:03,947 : INFO : EPOCH 2 - PROGRESS: at 99.24% examples, 92071 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:05,061 : INFO : EPOCH 2 - PROGRESS: at 99.25% examples, 92071 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:06,163 : INFO : EPOCH 2 - PROGRESS: at 99.26% examples, 92072 words/s, in_qsize 5, out_qsize 0
2021-02-23 20:00:07,278 : INFO : EPOCH 2 - PROGRESS: at 99.27% examples, 92073 words/s, in_qsize 5, out_

2021-02-23 20:01:32,285 : INFO : storing np array 'vectors_vocab' to ./notes_clean_fasttext_win10_min5_v2.dat.wv.vectors_vocab.npy
2021-02-23 20:01:32,631 : INFO : storing np array 'vectors_ngrams' to ./notes_clean_fasttext_win10_min5_v2.dat.wv.vectors_ngrams.npy
2021-02-23 20:01:34,266 : INFO : not storing attribute vectors_norm
2021-02-23 20:01:34,267 : INFO : not storing attribute vectors_vocab_norm
2021-02-23 20:01:34,268 : INFO : not storing attribute vectors_ngrams_norm
2021-02-23 20:01:34,269 : INFO : not storing attribute buckets_word
2021-02-23 20:01:34,270 : INFO : storing np array 'syn1neg' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.syn1neg.npy
2021-02-23 20:01:34,602 : INFO : storing np array 'vectors_vocab_lockf' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.vectors_vocab_lockf.npy
2021-02-23 20:01:34,933 : INFO : storing np array 'vectors_ngrams_lockf' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.vectors_ngrams_lockf.npy
2021-02-23 20:01:37,

first run - using text tokenised and cleaned using nltk:

2021-02-22 10:59:28,104 : INFO : collected 2019963 word types from a corpus of 2083112 raw words and 2083112 sentences
2021-02-22 10:59:28,104 : INFO : Loading a fresh vocabulary
2021-02-22 10:59:28,901 : INFO : effective_min_count=5 retains 1176 unique words (0% of original 2019963, drops 2018787)
2021-02-22 10:59:28,902 : INFO : effective_min_count=5 leaves 23371 word corpus (1% of original 2083112, drops 2059741)
2021-02-22 10:59:28,906 : INFO : deleting the raw counts dictionary of 2019963 items
2021-02-22 10:59:29,173 : INFO : sample=0.001 downsamples 38 most-common words
2021-02-22 10:59:29,174 : INFO : downsampling leaves estimated 15132 word corpus (64.7% of prior 23371)
2021-02-22 10:59:29,656 : INFO : estimated required memory for 1176 words, 78129 buckets and 300 dimensions: 110096912 bytes
2021-02-22 10:59:29,658 : INFO : resetting layer weights
2021-02-22 10:59:45,575 : INFO : training model with 3 workers on 1176 vocabulary and 300 features, using sg=0 hs=0 sample=0.001 negative=5 window=10
2021-02-22 11:00:02,367 : INFO : EPOCH - 1 : training on 2083112 raw words (15179 effective words) took 16.8s, 904 effective words/s
2021-02-22 11:00:19,226 : INFO : EPOCH - 2 : training on 2083112 raw words (15148 effective words) took 16.8s, 899 effective words/s
2021-02-22 11:00:19,227 : INFO : training on a 4166224 raw words (30327 effective words) took 33.7s, 901 effective words/s
2021-02-22 11:00:21,558 : INFO : saving FastText object under ./noteevents_clean_fasttext_win10_min5.dat, separately None
2021-02-22 11:00:21,559 : INFO : storing np array 'vectors_ngrams' to ./noteevents_clean_fasttext_win10_min5.dat.wv.vectors_ngrams.npy
2021-02-22 11:00:23,183 : INFO : not storing attribute vectors_norm
2021-02-22 11:00:23,184 : INFO : not storing attribute vectors_vocab_norm
2021-02-22 11:00:23,184 : INFO : not storing attribute vectors_ngrams_norm
2021-02-22 11:00:23,185 : INFO : not storing attribute buckets_word
2021-02-22 11:00:23,186 : INFO : storing np array 'vectors_ngrams_lockf' to ./noteevents_clean_fasttext_win10_min5.dat.trainables.vectors_ngrams_lockf.npy
2021-02-22 11:00:24,810 : INFO : saved ./noteevents_clean_fasttext_win10_min5.dat

second run - using text cleaned with spacy and this script

2021-02-23 17:06:28,169 : INFO : collected 1492743 word types from a corpus of 534796798 raw words and 2083180 sentences
2021-02-23 17:06:28,169 : INFO : Loading a fresh vocabulary
2021-02-23 17:06:29,998 : INFO : effective_min_count=5 retains 416342 unique words (27% of original 1492743, drops 1076401)
2021-02-23 17:06:29,999 : INFO : effective_min_count=5 leaves 533154263 word corpus (99% of original 534796798, drops 1642535)
2021-02-23 17:06:31,229 : INFO : deleting the raw counts dictionary of 1492743 items
2021-02-23 17:06:31,273 : INFO : sample=0.001 downsamples 35 most-common words
2021-02-23 17:06:31,274 : INFO : downsampling leaves estimated 476070309 word corpus (89.3% of prior 533154263)
2021-02-23 17:06:36,963 : INFO : estimated required memory for 416342 words, 1062221 buckets and 300 dimensions: 2583428840 bytes
2021-02-23 17:06:37,023 : INFO : resetting layer weights
2021-02-23 17:08:50,243 : INFO : training model with 3 workers on 416342 vocabulary and 300 features, using sg=0 hs=0 sample=0.001 negative=5 window=10
2021-02-23 18:35:02,395 : INFO : EPOCH - 1 : training on 534796798 raw words (476073678 effective words) took 5172.1s, 92046 effective words/s
2021-02-23 20:01:10,385 : INFO : EPOCH - 2 : training on 534796798 raw words (476061984 effective words) took 5168.0s, 92118 effective words/s
2021-02-23 20:01:10,386 : INFO : training on a 1069593596 raw words (952135662 effective words) took 10340.1s, 92081 effective words/s
2021-02-23 20:01:31,925 : INFO : saving FastText object under ./notes_clean_fasttext_win10_min5_v2.dat, separately None
2021-02-23 20:01:31,927 : INFO : storing np array 'vectors' to ./notes_clean_fasttext_win10_min5_v2.dat.wv.vectors.npy
2021-02-23 20:01:32,285 : INFO : storing np array 'vectors_vocab' to ./notes_clean_fasttext_win10_min5_v2.dat.wv.vectors_vocab.npy
2021-02-23 20:01:32,631 : INFO : storing np array 'vectors_ngrams' to ./notes_clean_fasttext_win10_min5_v2.dat.wv.vectors_ngrams.npy
2021-02-23 20:01:34,266 : INFO : not storing attribute vectors_norm
2021-02-23 20:01:34,267 : INFO : not storing attribute vectors_vocab_norm
2021-02-23 20:01:34,268 : INFO : not storing attribute vectors_ngrams_norm
2021-02-23 20:01:34,269 : INFO : not storing attribute buckets_word
2021-02-23 20:01:34,270 : INFO : storing np array 'syn1neg' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.syn1neg.npy
2021-02-23 20:01:34,602 : INFO : storing np array 'vectors_vocab_lockf' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.vectors_vocab_lockf.npy
2021-02-23 20:01:34,933 : INFO : storing np array 'vectors_ngrams_lockf' to ./notes_clean_fasttext_win10_min5_v2.dat.trainables.vectors_ngrams_lockf.npy
2021-02-23 20:01:37,458 : INFO : saved ./notes_clean_fasttext_win10_min5_v2.dat

## TRAIN W2v

In [41]:
# TRAIN AND SAVE W2V
w2v_model = Word2Vec(sentences, size=size, window=window, min_count=min_count, workers=workers)
w2v_model.save(filename.replace('.txt','_w2v_win10_min5_v2.dat'))

# test
w2v_model.wv.most_similar("pain")

2021-02-23 20:07:10,224 : INFO : collecting all words and their counts
2021-02-23 20:07:10,228 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2021-02-23 20:07:11,412 : INFO : PROGRESS: at sentence #10000, processed 4750988 words, keeping 47253 word types
2021-02-23 20:07:12,576 : INFO : PROGRESS: at sentence #20000, processed 9517988 words, keeping 70404 word types
2021-02-23 20:07:13,750 : INFO : PROGRESS: at sentence #30000, processed 14217892 words, keeping 89904 word types
2021-02-23 20:07:14,590 : INFO : PROGRESS: at sentence #40000, processed 17342834 words, keeping 108098 word types
2021-02-23 20:07:15,099 : INFO : PROGRESS: at sentence #50000, processed 19317065 words, keeping 123739 word types
2021-02-23 20:07:15,635 : INFO : PROGRESS: at sentence #60000, processed 21292462 words, keeping 137319 word types
2021-02-23 20:07:16,161 : INFO : PROGRESS: at sentence #70000, processed 23293819 words, keeping 149541 word types
2021-02-23 20:07:16,684 : INFO

2021-02-23 20:07:45,288 : INFO : PROGRESS: at sentence #710000, processed 129482719 words, keeping 690729 word types
2021-02-23 20:07:45,796 : INFO : PROGRESS: at sentence #720000, processed 131326251 words, keeping 698923 word types
2021-02-23 20:07:46,413 : INFO : PROGRESS: at sentence #730000, processed 133405061 words, keeping 707962 word types
2021-02-23 20:07:49,916 : INFO : PROGRESS: at sentence #740000, processed 146962855 words, keeping 765561 word types
2021-02-23 20:07:54,060 : INFO : PROGRESS: at sentence #750000, processed 162247244 words, keeping 810963 word types
2021-02-23 20:07:58,535 : INFO : PROGRESS: at sentence #760000, processed 178597370 words, keeping 851152 word types
2021-02-23 20:07:59,403 : INFO : PROGRESS: at sentence #770000, processed 181862498 words, keeping 853644 word types
2021-02-23 20:08:00,287 : INFO : PROGRESS: at sentence #780000, processed 185139730 words, keeping 854579 word types
2021-02-23 20:08:00,758 : INFO : PROGRESS: at sentence #790000, 

2021-02-23 20:08:45,859 : INFO : PROGRESS: at sentence #1410000, processed 352027794 words, keeping 1196703 word types
2021-02-23 20:08:49,340 : INFO : PROGRESS: at sentence #1420000, processed 365689697 words, keeping 1223064 word types
2021-02-23 20:08:50,136 : INFO : PROGRESS: at sentence #1430000, processed 368701155 words, keeping 1223883 word types
2021-02-23 20:08:50,321 : INFO : PROGRESS: at sentence #1440000, processed 369401663 words, keeping 1224097 word types
2021-02-23 20:08:50,409 : INFO : PROGRESS: at sentence #1450000, processed 369708850 words, keeping 1224238 word types
2021-02-23 20:08:50,492 : INFO : PROGRESS: at sentence #1460000, processed 370007394 words, keeping 1224371 word types
2021-02-23 20:08:50,574 : INFO : PROGRESS: at sentence #1470000, processed 370318348 words, keeping 1224472 word types
2021-02-23 20:08:50,662 : INFO : PROGRESS: at sentence #1480000, processed 370650534 words, keeping 1224658 word types
2021-02-23 20:08:51,410 : INFO : PROGRESS: at se

2021-02-23 20:09:36,486 : INFO : Loading a fresh vocabulary
2021-02-23 20:09:38,109 : INFO : effective_min_count=5 retains 416342 unique words (27% of original 1492743, drops 1076401)
2021-02-23 20:09:38,110 : INFO : effective_min_count=5 leaves 533154263 word corpus (99% of original 534796798, drops 1642535)
2021-02-23 20:09:39,344 : INFO : deleting the raw counts dictionary of 1492743 items
2021-02-23 20:09:39,391 : INFO : sample=0.001 downsamples 35 most-common words
2021-02-23 20:09:39,392 : INFO : downsampling leaves estimated 476070309 word corpus (89.3% of prior 533154263)
2021-02-23 20:09:40,739 : INFO : estimated required memory for 416342 words and 300 dimensions: 1207391800 bytes
2021-02-23 20:09:40,739 : INFO : resetting layer weights
2021-02-23 20:11:05,226 : INFO : training model with 16 workers on 416342 vocabulary and 300 features, using sg=0 hs=0 sample=0.001 negative=5 window=10
2021-02-23 20:11:06,243 : INFO : EPOCH 1 - PROGRESS: at 0.08% examples, 752630 words/s, in

2021-02-23 20:12:10,859 : INFO : EPOCH 1 - PROGRESS: at 16.06% examples, 1046634 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:12:11,865 : INFO : EPOCH 1 - PROGRESS: at 16.41% examples, 1046383 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:12:12,870 : INFO : EPOCH 1 - PROGRESS: at 16.75% examples, 1045505 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:12:13,873 : INFO : EPOCH 1 - PROGRESS: at 17.11% examples, 1045313 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:12:14,889 : INFO : EPOCH 1 - PROGRESS: at 17.46% examples, 1045360 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:12:15,890 : INFO : EPOCH 1 - PROGRESS: at 17.80% examples, 1044711 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:12:16,903 : INFO : EPOCH 1 - PROGRESS: at 18.13% examples, 1044035 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:12:17,905 : INFO : EPOCH 1 - PROGRESS: at 18.49% examples, 1043782 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:12:18,925 : INFO : EPOCH 1 - PROGRESS: at 18.82% examples, 1042435

2021-02-23 20:13:23,483 : INFO : EPOCH 1 - PROGRESS: at 35.99% examples, 1029422 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:13:24,489 : INFO : EPOCH 1 - PROGRESS: at 36.02% examples, 1029430 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:13:25,495 : INFO : EPOCH 1 - PROGRESS: at 36.05% examples, 1029421 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:13:26,498 : INFO : EPOCH 1 - PROGRESS: at 36.08% examples, 1029290 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:13:27,522 : INFO : EPOCH 1 - PROGRESS: at 36.12% examples, 1029067 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:13:28,537 : INFO : EPOCH 1 - PROGRESS: at 36.15% examples, 1029013 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:13:29,556 : INFO : EPOCH 1 - PROGRESS: at 36.18% examples, 1028956 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:13:30,562 : INFO : EPOCH 1 - PROGRESS: at 36.21% examples, 1028959 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:13:31,581 : INFO : EPOCH 1 - PROGRESS: at 36.24% examples, 1028710

2021-02-23 20:14:36,252 : INFO : EPOCH 1 - PROGRESS: at 48.58% examples, 1041755 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:14:37,267 : INFO : EPOCH 1 - PROGRESS: at 48.70% examples, 1041238 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:14:38,270 : INFO : EPOCH 1 - PROGRESS: at 48.82% examples, 1040876 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:14:39,282 : INFO : EPOCH 1 - PROGRESS: at 48.95% examples, 1041148 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:14:40,288 : INFO : EPOCH 1 - PROGRESS: at 49.07% examples, 1041194 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:14:41,313 : INFO : EPOCH 1 - PROGRESS: at 49.19% examples, 1041495 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:14:42,325 : INFO : EPOCH 1 - PROGRESS: at 49.32% examples, 1041590 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:14:43,340 : INFO : EPOCH 1 - PROGRESS: at 49.45% examples, 1041934 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:14:44,348 : INFO : EPOCH 1 - PROGRESS: at 49.58% examples, 1042108

2021-02-23 20:15:48,988 : INFO : EPOCH 1 - PROGRESS: at 63.77% examples, 1042068 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:15:49,997 : INFO : EPOCH 1 - PROGRESS: at 64.25% examples, 1041977 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:15:51,023 : INFO : EPOCH 1 - PROGRESS: at 64.75% examples, 1041894 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:15:52,029 : INFO : EPOCH 1 - PROGRESS: at 65.23% examples, 1041673 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:15:53,037 : INFO : EPOCH 1 - PROGRESS: at 65.73% examples, 1041657 words/s, in_qsize 28, out_qsize 2
2021-02-23 20:15:54,053 : INFO : EPOCH 1 - PROGRESS: at 66.21% examples, 1041554 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:15:55,068 : INFO : EPOCH 1 - PROGRESS: at 66.71% examples, 1041577 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:15:56,075 : INFO : EPOCH 1 - PROGRESS: at 67.05% examples, 1041436 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:15:57,080 : INFO : EPOCH 1 - PROGRESS: at 67.31% examples, 1041576

2021-02-23 20:17:01,649 : INFO : EPOCH 1 - PROGRESS: at 76.23% examples, 1048825 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:17:02,651 : INFO : EPOCH 1 - PROGRESS: at 76.37% examples, 1048972 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:17:03,660 : INFO : EPOCH 1 - PROGRESS: at 76.50% examples, 1049111 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:17:04,668 : INFO : EPOCH 1 - PROGRESS: at 76.63% examples, 1049273 words/s, in_qsize 31, out_qsize 2
2021-02-23 20:17:05,670 : INFO : EPOCH 1 - PROGRESS: at 76.75% examples, 1049207 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:17:06,671 : INFO : EPOCH 1 - PROGRESS: at 76.88% examples, 1049341 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:17:07,674 : INFO : EPOCH 1 - PROGRESS: at 77.01% examples, 1049531 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:17:08,689 : INFO : EPOCH 1 - PROGRESS: at 77.29% examples, 1049432 words/s, in_qsize 31, out_qsize 2
2021-02-23 20:17:09,695 : INFO : EPOCH 1 - PROGRESS: at 77.57% examples, 1049519

2021-02-23 20:18:14,176 : INFO : EPOCH 1 - PROGRESS: at 94.82% examples, 1047668 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:18:15,203 : INFO : EPOCH 1 - PROGRESS: at 94.86% examples, 1047507 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:18:16,205 : INFO : EPOCH 1 - PROGRESS: at 94.91% examples, 1047536 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:18:17,212 : INFO : EPOCH 1 - PROGRESS: at 94.96% examples, 1047566 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:18:18,213 : INFO : EPOCH 1 - PROGRESS: at 95.16% examples, 1047866 words/s, in_qsize 32, out_qsize 3
2021-02-23 20:18:19,222 : INFO : EPOCH 1 - PROGRESS: at 95.34% examples, 1048112 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:18:20,231 : INFO : EPOCH 1 - PROGRESS: at 95.81% examples, 1048112 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:18:21,235 : INFO : EPOCH 1 - PROGRESS: at 97.66% examples, 1048154 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:18:22,237 : INFO : EPOCH 1 - PROGRESS: at 97.84% examples, 1048192

2021-02-23 20:19:12,971 : INFO : EPOCH 2 - PROGRESS: at 7.76% examples, 1085616 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:19:13,971 : INFO : EPOCH 2 - PROGRESS: at 8.06% examples, 1086749 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:19:14,979 : INFO : EPOCH 2 - PROGRESS: at 8.34% examples, 1085280 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:19:15,993 : INFO : EPOCH 2 - PROGRESS: at 8.64% examples, 1084718 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:19:17,001 : INFO : EPOCH 2 - PROGRESS: at 8.94% examples, 1083694 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:19:18,028 : INFO : EPOCH 2 - PROGRESS: at 9.25% examples, 1083744 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:19:19,032 : INFO : EPOCH 2 - PROGRESS: at 9.56% examples, 1084971 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:19:20,040 : INFO : EPOCH 2 - PROGRESS: at 9.84% examples, 1084119 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:19:21,048 : INFO : EPOCH 2 - PROGRESS: at 10.13% examples, 1084670 words/s

2021-02-23 20:20:25,588 : INFO : EPOCH 2 - PROGRESS: at 33.63% examples, 1052090 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:20:26,589 : INFO : EPOCH 2 - PROGRESS: at 34.04% examples, 1051825 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:20:27,610 : INFO : EPOCH 2 - PROGRESS: at 34.25% examples, 1051079 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:20:28,620 : INFO : EPOCH 2 - PROGRESS: at 34.59% examples, 1050887 words/s, in_qsize 30, out_qsize 3
2021-02-23 20:20:29,658 : INFO : EPOCH 2 - PROGRESS: at 34.76% examples, 1050974 words/s, in_qsize 30, out_qsize 4
2021-02-23 20:20:30,663 : INFO : EPOCH 2 - PROGRESS: at 35.10% examples, 1051892 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:20:31,684 : INFO : EPOCH 2 - PROGRESS: at 35.13% examples, 1051339 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:20:32,692 : INFO : EPOCH 2 - PROGRESS: at 35.17% examples, 1051787 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:20:33,696 : INFO : EPOCH 2 - PROGRESS: at 35.20% examples, 1051638

2021-02-23 20:21:38,383 : INFO : EPOCH 2 - PROGRESS: at 45.19% examples, 1056661 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:21:39,385 : INFO : EPOCH 2 - PROGRESS: at 45.33% examples, 1056980 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:21:40,392 : INFO : EPOCH 2 - PROGRESS: at 45.46% examples, 1057143 words/s, in_qsize 28, out_qsize 3
2021-02-23 20:21:41,394 : INFO : EPOCH 2 - PROGRESS: at 45.59% examples, 1057350 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:21:42,411 : INFO : EPOCH 2 - PROGRESS: at 45.72% examples, 1057405 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:21:43,418 : INFO : EPOCH 2 - PROGRESS: at 45.84% examples, 1057729 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:21:44,427 : INFO : EPOCH 2 - PROGRESS: at 45.97% examples, 1057950 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:21:45,433 : INFO : EPOCH 2 - PROGRESS: at 46.10% examples, 1058061 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:21:46,445 : INFO : EPOCH 2 - PROGRESS: at 46.22% examples, 1058178

2021-02-23 20:22:50,959 : INFO : EPOCH 2 - PROGRESS: at 55.47% examples, 1066232 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:22:51,963 : INFO : EPOCH 2 - PROGRESS: at 55.74% examples, 1066145 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:22:52,963 : INFO : EPOCH 2 - PROGRESS: at 56.01% examples, 1066086 words/s, in_qsize 29, out_qsize 0
2021-02-23 20:22:53,964 : INFO : EPOCH 2 - PROGRESS: at 56.28% examples, 1066014 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:22:54,978 : INFO : EPOCH 2 - PROGRESS: at 56.55% examples, 1066120 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:22:55,986 : INFO : EPOCH 2 - PROGRESS: at 56.82% examples, 1066220 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:22:56,986 : INFO : EPOCH 2 - PROGRESS: at 57.08% examples, 1066239 words/s, in_qsize 30, out_qsize 0
2021-02-23 20:22:57,995 : INFO : EPOCH 2 - PROGRESS: at 57.32% examples, 1066162 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:22:59,003 : INFO : EPOCH 2 - PROGRESS: at 57.62% examples, 1066193

2021-02-23 20:24:03,692 : INFO : EPOCH 2 - PROGRESS: at 73.08% examples, 1064991 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:24:04,697 : INFO : EPOCH 2 - PROGRESS: at 73.21% examples, 1065123 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:24:05,698 : INFO : EPOCH 2 - PROGRESS: at 73.34% examples, 1065237 words/s, in_qsize 29, out_qsize 0
2021-02-23 20:24:06,705 : INFO : EPOCH 2 - PROGRESS: at 73.48% examples, 1065267 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:24:07,723 : INFO : EPOCH 2 - PROGRESS: at 73.61% examples, 1065329 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:24:08,732 : INFO : EPOCH 2 - PROGRESS: at 73.73% examples, 1065294 words/s, in_qsize 32, out_qsize 4
2021-02-23 20:24:09,733 : INFO : EPOCH 2 - PROGRESS: at 73.86% examples, 1065600 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:24:10,738 : INFO : EPOCH 2 - PROGRESS: at 73.98% examples, 1065627 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:24:11,753 : INFO : EPOCH 2 - PROGRESS: at 74.10% examples, 1065732

2021-02-23 20:25:16,320 : INFO : EPOCH 2 - PROGRESS: at 89.61% examples, 1066359 words/s, in_qsize 30, out_qsize 4
2021-02-23 20:25:17,323 : INFO : EPOCH 2 - PROGRESS: at 90.04% examples, 1066312 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:25:18,328 : INFO : EPOCH 2 - PROGRESS: at 90.49% examples, 1066070 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:25:19,329 : INFO : EPOCH 2 - PROGRESS: at 91.00% examples, 1066015 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:25:20,331 : INFO : EPOCH 2 - PROGRESS: at 91.51% examples, 1065917 words/s, in_qsize 31, out_qsize 3
2021-02-23 20:25:21,349 : INFO : EPOCH 2 - PROGRESS: at 91.99% examples, 1065773 words/s, in_qsize 31, out_qsize 4
2021-02-23 20:25:22,373 : INFO : EPOCH 2 - PROGRESS: at 92.51% examples, 1065742 words/s, in_qsize 28, out_qsize 3
2021-02-23 20:25:23,420 : INFO : EPOCH 2 - PROGRESS: at 92.95% examples, 1065533 words/s, in_qsize 32, out_qsize 3
2021-02-23 20:25:24,427 : INFO : EPOCH 2 - PROGRESS: at 93.42% examples, 1065464

2021-02-23 20:26:15,847 : INFO : EPOCH 3 - PROGRESS: at 1.38% examples, 1113130 words/s, in_qsize 30, out_qsize 3
2021-02-23 20:26:16,862 : INFO : EPOCH 3 - PROGRESS: at 1.50% examples, 1117972 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:26:17,865 : INFO : EPOCH 3 - PROGRESS: at 1.64% examples, 1116033 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:26:18,873 : INFO : EPOCH 3 - PROGRESS: at 1.92% examples, 1114721 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:26:19,878 : INFO : EPOCH 3 - PROGRESS: at 2.22% examples, 1110230 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:26:20,892 : INFO : EPOCH 3 - PROGRESS: at 2.54% examples, 1110609 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:26:21,910 : INFO : EPOCH 3 - PROGRESS: at 2.85% examples, 1106813 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:26:22,915 : INFO : EPOCH 3 - PROGRESS: at 3.14% examples, 1103893 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:26:23,928 : INFO : EPOCH 3 - PROGRESS: at 3.45% examples, 1103688 words/s,

2021-02-23 20:27:28,635 : INFO : EPOCH 3 - PROGRESS: at 22.92% examples, 1060518 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:27:29,644 : INFO : EPOCH 3 - PROGRESS: at 23.27% examples, 1060121 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:27:30,647 : INFO : EPOCH 3 - PROGRESS: at 23.62% examples, 1060230 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:27:31,651 : INFO : EPOCH 3 - PROGRESS: at 23.97% examples, 1059657 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:27:32,658 : INFO : EPOCH 3 - PROGRESS: at 24.40% examples, 1059454 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:27:33,683 : INFO : EPOCH 3 - PROGRESS: at 24.80% examples, 1058080 words/s, in_qsize 29, out_qsize 6
2021-02-23 20:27:34,687 : INFO : EPOCH 3 - PROGRESS: at 25.22% examples, 1057857 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:27:35,689 : INFO : EPOCH 3 - PROGRESS: at 25.74% examples, 1057894 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:27:36,692 : INFO : EPOCH 3 - PROGRESS: at 26.23% examples, 1057269

2021-02-23 20:28:41,468 : INFO : EPOCH 3 - PROGRESS: at 39.02% examples, 1053926 words/s, in_qsize 26, out_qsize 7
2021-02-23 20:28:42,483 : INFO : EPOCH 3 - PROGRESS: at 40.96% examples, 1054050 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:28:43,490 : INFO : EPOCH 3 - PROGRESS: at 42.61% examples, 1054470 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:28:44,490 : INFO : EPOCH 3 - PROGRESS: at 42.82% examples, 1054638 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:28:45,495 : INFO : EPOCH 3 - PROGRESS: at 42.98% examples, 1054961 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:28:46,511 : INFO : EPOCH 3 - PROGRESS: at 43.11% examples, 1055147 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:28:47,514 : INFO : EPOCH 3 - PROGRESS: at 43.22% examples, 1055320 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:28:48,517 : INFO : EPOCH 3 - PROGRESS: at 43.34% examples, 1055251 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:28:49,526 : INFO : EPOCH 3 - PROGRESS: at 43.46% examples, 1055390

2021-02-23 20:29:54,147 : INFO : EPOCH 3 - PROGRESS: at 51.45% examples, 1067686 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:29:55,156 : INFO : EPOCH 3 - PROGRESS: at 51.57% examples, 1067556 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:29:56,168 : INFO : EPOCH 3 - PROGRESS: at 51.70% examples, 1067830 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:29:57,185 : INFO : EPOCH 3 - PROGRESS: at 51.83% examples, 1068137 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:29:58,196 : INFO : EPOCH 3 - PROGRESS: at 51.95% examples, 1068236 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:29:59,197 : INFO : EPOCH 3 - PROGRESS: at 52.07% examples, 1068484 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:30:00,208 : INFO : EPOCH 3 - PROGRESS: at 52.20% examples, 1068642 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:30:01,210 : INFO : EPOCH 3 - PROGRESS: at 52.32% examples, 1068553 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:30:02,234 : INFO : EPOCH 3 - PROGRESS: at 52.44% examples, 1068673

2021-02-23 20:31:06,872 : INFO : EPOCH 3 - PROGRESS: at 67.94% examples, 1063349 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:07,895 : INFO : EPOCH 3 - PROGRESS: at 67.97% examples, 1063156 words/s, in_qsize 32, out_qsize 3
2021-02-23 20:31:08,917 : INFO : EPOCH 3 - PROGRESS: at 68.01% examples, 1063193 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:09,937 : INFO : EPOCH 3 - PROGRESS: at 68.06% examples, 1063067 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:10,941 : INFO : EPOCH 3 - PROGRESS: at 68.25% examples, 1063547 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:11,942 : INFO : EPOCH 3 - PROGRESS: at 68.45% examples, 1063652 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:12,955 : INFO : EPOCH 3 - PROGRESS: at 68.66% examples, 1063692 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:13,964 : INFO : EPOCH 3 - PROGRESS: at 70.06% examples, 1063733 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:31:14,968 : INFO : EPOCH 3 - PROGRESS: at 71.20% examples, 1064028

2021-02-23 20:32:19,558 : INFO : EPOCH 3 - PROGRESS: at 82.54% examples, 1068610 words/s, in_qsize 28, out_qsize 4
2021-02-23 20:32:20,562 : INFO : EPOCH 3 - PROGRESS: at 82.84% examples, 1068650 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:32:21,586 : INFO : EPOCH 3 - PROGRESS: at 83.11% examples, 1068482 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:32:22,616 : INFO : EPOCH 3 - PROGRESS: at 83.37% examples, 1068399 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:32:23,620 : INFO : EPOCH 3 - PROGRESS: at 83.63% examples, 1068343 words/s, in_qsize 28, out_qsize 3
2021-02-23 20:32:24,624 : INFO : EPOCH 3 - PROGRESS: at 83.90% examples, 1068326 words/s, in_qsize 29, out_qsize 0
2021-02-23 20:32:25,640 : INFO : EPOCH 3 - PROGRESS: at 84.18% examples, 1068318 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:32:26,646 : INFO : EPOCH 3 - PROGRESS: at 84.44% examples, 1068328 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:32:27,651 : INFO : EPOCH 3 - PROGRESS: at 84.69% examples, 1068240

2021-02-23 20:33:31,209 : INFO : worker thread finished; awaiting finish of 14 more threads
2021-02-23 20:33:31,214 : INFO : worker thread finished; awaiting finish of 13 more threads
2021-02-23 20:33:31,231 : INFO : worker thread finished; awaiting finish of 12 more threads
2021-02-23 20:33:31,233 : INFO : worker thread finished; awaiting finish of 11 more threads
2021-02-23 20:33:31,237 : INFO : worker thread finished; awaiting finish of 10 more threads
2021-02-23 20:33:31,239 : INFO : worker thread finished; awaiting finish of 9 more threads
2021-02-23 20:33:31,242 : INFO : worker thread finished; awaiting finish of 8 more threads
2021-02-23 20:33:31,243 : INFO : worker thread finished; awaiting finish of 7 more threads
2021-02-23 20:33:31,251 : INFO : worker thread finished; awaiting finish of 6 more threads
2021-02-23 20:33:31,256 : INFO : worker thread finished; awaiting finish of 5 more threads
2021-02-23 20:33:31,261 : INFO : worker thread finished; awaiting finish of 4 more th

2021-02-23 20:34:31,887 : INFO : EPOCH 4 - PROGRESS: at 14.73% examples, 1067486 words/s, in_qsize 32, out_qsize 2
2021-02-23 20:34:32,895 : INFO : EPOCH 4 - PROGRESS: at 15.08% examples, 1066846 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:34:33,895 : INFO : EPOCH 4 - PROGRESS: at 15.42% examples, 1066040 words/s, in_qsize 30, out_qsize 3
2021-02-23 20:34:34,914 : INFO : EPOCH 4 - PROGRESS: at 15.76% examples, 1065555 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:34:35,923 : INFO : EPOCH 4 - PROGRESS: at 16.12% examples, 1065605 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:34:36,945 : INFO : EPOCH 4 - PROGRESS: at 16.48% examples, 1064796 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:34:37,946 : INFO : EPOCH 4 - PROGRESS: at 16.83% examples, 1064228 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:34:38,950 : INFO : EPOCH 4 - PROGRESS: at 17.18% examples, 1063735 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:34:39,959 : INFO : EPOCH 4 - PROGRESS: at 17.52% examples, 1062886

2021-02-23 20:35:44,604 : INFO : EPOCH 4 - PROGRESS: at 35.89% examples, 1044538 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:35:45,611 : INFO : EPOCH 4 - PROGRESS: at 35.92% examples, 1044600 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:35:46,622 : INFO : EPOCH 4 - PROGRESS: at 35.96% examples, 1044079 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:35:47,623 : INFO : EPOCH 4 - PROGRESS: at 35.99% examples, 1044404 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:35:48,632 : INFO : EPOCH 4 - PROGRESS: at 36.02% examples, 1044114 words/s, in_qsize 28, out_qsize 3
2021-02-23 20:35:49,641 : INFO : EPOCH 4 - PROGRESS: at 36.05% examples, 1043911 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:35:50,643 : INFO : EPOCH 4 - PROGRESS: at 36.09% examples, 1044467 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:35:51,647 : INFO : EPOCH 4 - PROGRESS: at 36.12% examples, 1043913 words/s, in_qsize 32, out_qsize 2
2021-02-23 20:35:52,649 : INFO : EPOCH 4 - PROGRESS: at 36.15% examples, 1043901

2021-02-23 20:36:57,126 : INFO : EPOCH 4 - PROGRESS: at 48.32% examples, 1057272 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:36:58,135 : INFO : EPOCH 4 - PROGRESS: at 48.43% examples, 1057076 words/s, in_qsize 27, out_qsize 6
2021-02-23 20:36:59,137 : INFO : EPOCH 4 - PROGRESS: at 48.58% examples, 1057466 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:37:00,137 : INFO : EPOCH 4 - PROGRESS: at 48.71% examples, 1057700 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:37:01,141 : INFO : EPOCH 4 - PROGRESS: at 48.84% examples, 1057682 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:37:02,143 : INFO : EPOCH 4 - PROGRESS: at 48.97% examples, 1057779 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:37:03,173 : INFO : EPOCH 4 - PROGRESS: at 49.09% examples, 1057771 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:37:04,174 : INFO : EPOCH 4 - PROGRESS: at 49.21% examples, 1058069 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:37:05,191 : INFO : EPOCH 4 - PROGRESS: at 49.35% examples, 1058397

2021-02-23 20:38:09,969 : INFO : EPOCH 4 - PROGRESS: at 63.52% examples, 1059179 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:38:10,986 : INFO : EPOCH 4 - PROGRESS: at 64.00% examples, 1059022 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:38:12,002 : INFO : EPOCH 4 - PROGRESS: at 64.50% examples, 1058881 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:38:13,010 : INFO : EPOCH 4 - PROGRESS: at 65.02% examples, 1058967 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:38:14,016 : INFO : EPOCH 4 - PROGRESS: at 65.54% examples, 1059051 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:38:15,022 : INFO : EPOCH 4 - PROGRESS: at 66.00% examples, 1058644 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:38:16,030 : INFO : EPOCH 4 - PROGRESS: at 66.49% examples, 1058537 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:38:17,046 : INFO : EPOCH 4 - PROGRESS: at 66.93% examples, 1058448 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:38:18,058 : INFO : EPOCH 4 - PROGRESS: at 67.15% examples, 1058237

2021-02-23 20:39:22,653 : INFO : EPOCH 4 - PROGRESS: at 76.14% examples, 1061609 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:39:23,658 : INFO : EPOCH 4 - PROGRESS: at 76.26% examples, 1061644 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:39:24,683 : INFO : EPOCH 4 - PROGRESS: at 76.40% examples, 1061699 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:39:25,684 : INFO : EPOCH 4 - PROGRESS: at 76.53% examples, 1061924 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:39:26,684 : INFO : EPOCH 4 - PROGRESS: at 76.66% examples, 1061910 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:39:27,697 : INFO : EPOCH 4 - PROGRESS: at 76.79% examples, 1062130 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:39:28,703 : INFO : EPOCH 4 - PROGRESS: at 76.93% examples, 1062377 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:39:29,707 : INFO : EPOCH 4 - PROGRESS: at 77.10% examples, 1062340 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:39:30,715 : INFO : EPOCH 4 - PROGRESS: at 77.40% examples, 1062454

2021-02-23 20:40:35,366 : INFO : EPOCH 4 - PROGRESS: at 94.80% examples, 1057900 words/s, in_qsize 28, out_qsize 1
2021-02-23 20:40:36,375 : INFO : EPOCH 4 - PROGRESS: at 94.83% examples, 1057746 words/s, in_qsize 27, out_qsize 4
2021-02-23 20:40:37,383 : INFO : EPOCH 4 - PROGRESS: at 94.88% examples, 1057915 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:40:38,391 : INFO : EPOCH 4 - PROGRESS: at 94.92% examples, 1057853 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:40:39,401 : INFO : EPOCH 4 - PROGRESS: at 95.02% examples, 1057906 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:40:40,407 : INFO : EPOCH 4 - PROGRESS: at 95.23% examples, 1058247 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:40:41,415 : INFO : EPOCH 4 - PROGRESS: at 95.41% examples, 1058430 words/s, in_qsize 29, out_qsize 2
2021-02-23 20:40:42,420 : INFO : EPOCH 4 - PROGRESS: at 96.58% examples, 1058534 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:40:43,449 : INFO : EPOCH 4 - PROGRESS: at 97.77% examples, 1058560

2021-02-23 20:41:34,798 : INFO : EPOCH 5 - PROGRESS: at 7.68% examples, 1077630 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:41:35,804 : INFO : EPOCH 5 - PROGRESS: at 7.95% examples, 1076609 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:36,813 : INFO : EPOCH 5 - PROGRESS: at 8.23% examples, 1075989 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:37,827 : INFO : EPOCH 5 - PROGRESS: at 8.52% examples, 1074546 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:38,845 : INFO : EPOCH 5 - PROGRESS: at 8.83% examples, 1074419 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:41:39,849 : INFO : EPOCH 5 - PROGRESS: at 9.12% examples, 1073378 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:40,851 : INFO : EPOCH 5 - PROGRESS: at 9.40% examples, 1071839 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:41,854 : INFO : EPOCH 5 - PROGRESS: at 9.69% examples, 1071613 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:41:42,867 : INFO : EPOCH 5 - PROGRESS: at 9.97% examples, 1071042 words/s,

2021-02-23 20:42:47,575 : INFO : EPOCH 5 - PROGRESS: at 33.25% examples, 1043536 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:42:48,576 : INFO : EPOCH 5 - PROGRESS: at 33.73% examples, 1043147 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:42:49,630 : INFO : EPOCH 5 - PROGRESS: at 34.09% examples, 1042777 words/s, in_qsize 31, out_qsize 5
2021-02-23 20:42:50,635 : INFO : EPOCH 5 - PROGRESS: at 34.35% examples, 1042433 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:42:51,638 : INFO : EPOCH 5 - PROGRESS: at 34.63% examples, 1042640 words/s, in_qsize 30, out_qsize 3
2021-02-23 20:42:52,649 : INFO : EPOCH 5 - PROGRESS: at 34.89% examples, 1042883 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:42:53,651 : INFO : EPOCH 5 - PROGRESS: at 35.10% examples, 1042522 words/s, in_qsize 30, out_qsize 0
2021-02-23 20:42:54,655 : INFO : EPOCH 5 - PROGRESS: at 35.14% examples, 1042608 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:42:55,669 : INFO : EPOCH 5 - PROGRESS: at 35.17% examples, 1042702

2021-02-23 20:44:00,236 : INFO : EPOCH 5 - PROGRESS: at 45.07% examples, 1050272 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:44:01,241 : INFO : EPOCH 5 - PROGRESS: at 45.19% examples, 1050684 words/s, in_qsize 30, out_qsize 2
2021-02-23 20:44:02,243 : INFO : EPOCH 5 - PROGRESS: at 45.32% examples, 1050789 words/s, in_qsize 31, out_qsize 3
2021-02-23 20:44:03,244 : INFO : EPOCH 5 - PROGRESS: at 45.46% examples, 1051398 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:44:04,247 : INFO : EPOCH 5 - PROGRESS: at 45.59% examples, 1051538 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:44:05,247 : INFO : EPOCH 5 - PROGRESS: at 45.71% examples, 1051490 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:44:06,266 : INFO : EPOCH 5 - PROGRESS: at 45.83% examples, 1051721 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:44:07,291 : INFO : EPOCH 5 - PROGRESS: at 45.97% examples, 1052118 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:44:08,307 : INFO : EPOCH 5 - PROGRESS: at 46.10% examples, 1052445

2021-02-23 20:45:12,948 : INFO : EPOCH 5 - PROGRESS: at 55.20% examples, 1061756 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:45:13,957 : INFO : EPOCH 5 - PROGRESS: at 55.50% examples, 1062005 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:45:14,972 : INFO : EPOCH 5 - PROGRESS: at 55.76% examples, 1061597 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:45:15,977 : INFO : EPOCH 5 - PROGRESS: at 56.03% examples, 1061531 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:45:16,980 : INFO : EPOCH 5 - PROGRESS: at 56.30% examples, 1061559 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:45:17,985 : INFO : EPOCH 5 - PROGRESS: at 56.56% examples, 1061528 words/s, in_qsize 30, out_qsize 0
2021-02-23 20:45:18,992 : INFO : EPOCH 5 - PROGRESS: at 56.81% examples, 1061388 words/s, in_qsize 31, out_qsize 1
2021-02-23 20:45:20,010 : INFO : EPOCH 5 - PROGRESS: at 57.06% examples, 1061254 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:45:21,039 : INFO : EPOCH 5 - PROGRESS: at 57.31% examples, 1061081

2021-02-23 20:46:25,865 : INFO : EPOCH 5 - PROGRESS: at 72.91% examples, 1058850 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:46:26,882 : INFO : EPOCH 5 - PROGRESS: at 73.02% examples, 1058841 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:46:27,895 : INFO : EPOCH 5 - PROGRESS: at 73.15% examples, 1059102 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:46:28,901 : INFO : EPOCH 5 - PROGRESS: at 73.27% examples, 1059060 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:46:29,919 : INFO : EPOCH 5 - PROGRESS: at 73.39% examples, 1058870 words/s, in_qsize 22, out_qsize 9
2021-02-23 20:46:30,922 : INFO : EPOCH 5 - PROGRESS: at 73.53% examples, 1059082 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:46:31,925 : INFO : EPOCH 5 - PROGRESS: at 73.66% examples, 1059199 words/s, in_qsize 30, out_qsize 1
2021-02-23 20:46:32,934 : INFO : EPOCH 5 - PROGRESS: at 73.79% examples, 1059356 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:46:33,944 : INFO : EPOCH 5 - PROGRESS: at 73.91% examples, 1059512

2021-02-23 20:47:38,573 : INFO : EPOCH 5 - PROGRESS: at 88.87% examples, 1059846 words/s, in_qsize 32, out_qsize 0
2021-02-23 20:47:39,601 : INFO : EPOCH 5 - PROGRESS: at 89.22% examples, 1059640 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:47:40,605 : INFO : EPOCH 5 - PROGRESS: at 89.58% examples, 1059722 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:47:41,639 : INFO : EPOCH 5 - PROGRESS: at 90.00% examples, 1059565 words/s, in_qsize 31, out_qsize 2
2021-02-23 20:47:42,684 : INFO : EPOCH 5 - PROGRESS: at 90.47% examples, 1059386 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:47:43,696 : INFO : EPOCH 5 - PROGRESS: at 90.99% examples, 1059321 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:47:44,705 : INFO : EPOCH 5 - PROGRESS: at 91.50% examples, 1059265 words/s, in_qsize 32, out_qsize 1
2021-02-23 20:47:45,712 : INFO : EPOCH 5 - PROGRESS: at 91.99% examples, 1059192 words/s, in_qsize 31, out_qsize 0
2021-02-23 20:47:46,724 : INFO : EPOCH 5 - PROGRESS: at 92.47% examples, 1059034

[('discomfort', 0.8041051626205444),
 ('pain-', 0.7034913897514343),
 ('apin', 0.6237826347351074),
 ('pian', 0.6045260429382324),
 ('soreness', 0.5998637676239014),
 ('pain/', 0.5868990421295166),
 ('cramping', 0.5682056546211243),
 ('pain\n', 0.5675026774406433),
 ('discomfort-', 0.5263482928276062),
 ('ache', 0.5159716606140137)]

first run - using text tokenised and cleaned using nltk:

2021-02-22 11:04:46,937 : INFO : collected 2019963 word types from a corpus of 2083112 raw words and 2083112 sentences
2021-02-22 11:04:46,938 : INFO : Loading a fresh vocabulary
2021-02-22 11:04:47,731 : INFO : effective_min_count=5 retains 1176 unique words (0% of original 2019963, drops 2018787)
2021-02-22 11:04:47,732 : INFO : effective_min_count=5 leaves 23371 word corpus (1% of original 2083112, drops 2059741)
2021-02-22 11:04:47,736 : INFO : deleting the raw counts dictionary of 2019963 items
2021-02-22 11:04:47,993 : INFO : sample=0.001 downsamples 38 most-common words
2021-02-22 11:04:47,994 : INFO : downsampling leaves estimated 15132 word corpus (64.7% of prior 23371)
2021-02-22 11:04:47,997 : INFO : estimated required memory for 1176 words and 300 dimensions: 3410400 bytes
2021-02-22 11:04:47,998 : INFO : resetting layer weights
2021-02-22 11:04:48,240 : INFO : training model with 16 workers on 1176 vocabulary and 300 features, using sg=0 hs=0 sample=0.001 negative=5 window=10
2021-02-22 11:05:06,369 : INFO : EPOCH - 1 : training on 2083112 raw words (15121 effective words) took 18.1s, 834 effective words/s
2021-02-22 11:05:24,363 : INFO : EPOCH - 2 : training on 2083112 raw words (15131 effective words) took 18.0s, 841 effective words/s
2021-02-22 11:05:42,383 : INFO : EPOCH - 3 : training on 2083112 raw words (15072 effective words) took 18.0s, 837 effective words/s
2021-02-22 11:05:59,885 : INFO : EPOCH - 4 : training on 2083112 raw words (15144 effective words) took 17.5s, 866 effective words/s
2021-02-22 11:06:17,620 : INFO : EPOCH - 5 : training on 2083112 raw words (15152 effective words) took 17.7s, 855 effective words/s
2021-02-22 11:06:17,621 : INFO : training on a 10415560 raw words (75620 effective words) took 89.4s, 846 effective words/s
2021-02-22 11:06:17,622 : INFO : saving Word2Vec object under ./noteevents_clean_fasttext_win10_min5.dat, separately None
2021-02-22 11:06:17,623 : INFO : not storing attribute vectors_norm
2021-02-22 11:06:17,624 : INFO : not storing attribute cum_table
2021-02-22 11:06:17,641 : INFO : saved ./noteevents_clean_fasttext_win10_min5.dat
2021-02-22 11:06:17,642 : INFO : precomputing L2-norms of word weight vectors

second run - using text cleaned with spacy and this script

2021-02-23 20:09:36,485 : INFO : collected 1492743 word types from a corpus of 534796798 raw words and 2083180 sentences
2021-02-23 20:09:36,486 : INFO : Loading a fresh vocabulary
2021-02-23 20:09:38,109 : INFO : effective_min_count=5 retains 416342 unique words (27% of original 1492743, drops 1076401)
2021-02-23 20:09:38,110 : INFO : effective_min_count=5 leaves 533154263 word corpus (99% of original 534796798, drops 1642535)
2021-02-23 20:09:39,344 : INFO : deleting the raw counts dictionary of 1492743 items
2021-02-23 20:09:39,391 : INFO : sample=0.001 downsamples 35 most-common words
2021-02-23 20:09:39,392 : INFO : downsampling leaves estimated 476070309 word corpus (89.3% of prior 533154263)
2021-02-23 20:09:40,739 : INFO : estimated required memory for 416342 words and 300 dimensions: 1207391800 bytes
2021-02-23 20:09:40,739 : INFO : resetting layer weights
2021-02-23 20:11:05,226 : INFO : training model with 16 workers on 416342 vocabulary and 300 features, using sg=0 hs=0 sample=0.001 negative=5 window=10
2021-02-23 20:18:38,538 : INFO : EPOCH - 1 : training on 534796798 raw words (476062716 effective words) took 453.3s, 1050207 effective words/s
2021-02-23 20:26:04,708 : INFO : EPOCH - 2 : training on 534796798 raw words (476069483 effective words) took 446.2s, 1067028 effective words/s
2021-02-23 20:33:31,278 : INFO : EPOCH - 3 : training on 534796798 raw words (476083085 effective words) took 446.6s, 1066103 effective words/s
2021-02-23 20:41:00,405 : INFO : EPOCH - 4 : training on 534796798 raw words (476073531 effective words) took 449.1s, 1060016 effective words/s
2021-02-23 20:48:29,504 : INFO : EPOCH - 5 : training on 534796798 raw words (476069393 effective words) took 449.1s, 1060066 effective words/s
2021-02-23 20:48:29,506 : INFO : training on a 2673983990 raw words (2380358208 effective words) took 2244.3s, 1060634 effective words/s
2021-02-23 20:48:29,507 : INFO : saving Word2Vec object under ./notes_clean_w2v_win10_min5_v2.dat, separately None
2021-02-23 20:48:29,508 : INFO : storing np array 'vectors' to ./notes_clean_w2v_win10_min5_v2.dat.wv.vectors.npy
2021-02-23 20:48:29,855 : INFO : not storing attribute vectors_norm
2021-02-23 20:48:29,856 : INFO : storing np array 'syn1neg' to ./notes_clean_w2v_win10_min5_v2.dat.trainables.syn1neg.npy
2021-02-23 20:48:30,195 : INFO : not storing attribute cum_table
2021-02-23 20:48:31,003 : INFO : saved ./notes_clean_w2v_win10_min5_v2.dat
2021-02-23 20:48:31,004 : INFO : precomputing L2-norms of word weight vectors

In [42]:
# test
w2v_model.wv.most_similar("pain")

[('discomfort', 0.8041051626205444),
 ('pain-', 0.7034913897514343),
 ('apin', 0.6237826347351074),
 ('pian', 0.6045260429382324),
 ('soreness', 0.5998637676239014),
 ('pain/', 0.5868990421295166),
 ('cramping', 0.5682056546211243),
 ('pain\n', 0.5675026774406433),
 ('discomfort-', 0.5263482928276062),
 ('ache', 0.5159716606140137)]

## TRAIN TFIDF

In [ ]:
# TRAIN AND SAVE TFIDF (USING SKLEARN - DOESN'T SEEM TO WORK ON BIG DATASETS)
tfidf = TfidfVectorizer(min_df=min_df, max_df=max_df, ngram_range=ngram_range, sublinear_tf=True, use_idf=True, 
                        max_features=max_features, preprocessor=' '.join)
trained_tfidf = tfidf.fit(sentences)
with open(filename.replace('.txt','_tfidf.pickle'), 'wb') as fin:
          pickle.dump(trained_tfidf, fin)

In [ ]:
# TRAIN AND SAVE TFIDF (UING GENSIM)

# Create the Dictionary and Corpus
mydict = corpora.Dictionary(sentences) # create dctionary
mydict.save(filename.replace('.txt','_tfidfdict.dict'))  # save dict to disk
corpus = [mydict.doc2bow(line) for line in sentences] # create corpus
corpora.MmCorpus.serialize(filename.replace('.txt','_tfidfcorpus.mm'), corpus)  # save corpus to disk

tfidf_model = TfidfModel(corpus)  # fit model
tfidf_model.save(filename.replace('.txt','_tfidf.model')) # save model